In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import os

In [2]:
# Provinces in Indonesia list
provinces = ["Aceh", "Riau", "Bengkulu", "Sumatera Selatan", "Sumatera Barat", "Sumatera Utara", "Jambi", "Lampung"]

In [54]:
# Get csv files with company information

# Change directory to access all csv files
cwd = os.getcwd() # Get current working directory
list_cwd = os.listdir() # List all files and directories inside the present one
os.chdir(cwd + "\\" + list_cwd[1]) # Change directory to the one with the csv's

# Get all csvs
companies_list = os.listdir()

NotADirectoryError: [WinError 267] El nombre del directorio no es válido: 'c:\\Users\\gabri\\Documents\\Chicago\\Palm_watch\\PalmWatch\\Companies_Indonesia\\Companies_Indonesia\\PalmWatch_mill_csv\\Colgate-Palmolive-Mills-2026-7-27.csv'

In [158]:
# Dictionary for company dataframe information
companies = {}

# Save the company name and the dataframe
for company in companies_list:

    name = company.split("-")[0] # Get the first word of the file name
    companies[name] = pd.read_csv(company) # Save csv as dataframe
    
companies

{'Colgate':             UML ID                     years               Group Name  \
 0     PO1000000019  2021,2020,2019,2018,2017  KULIM (MALAYSIA) BERHAD
 1     PO1000000020                      2018                    NBPOL
 2     PO1000000021  2018,2017,2020,2021,2019       ROYAL GOLDEN EAGLE
 3     PO1000000052       2021,2019,2018,2020          IOI CORPORATION
 4     PO1000000054       2021,2019,2017,2018                MUSIM MAS
 ...            ...                       ...                      ...
 1679  PO1000012845                      2021                  UNKNOWN
 1680  PO1000012846                      2021                  UNKNOWN
 1681  PO1000012848            2021,2019,2020                  UNKNOWN
 1682  PO1000012851                      2021                  UNKNOWN
 1683  PO1000012852                      2021                  UNKNOWN

                      Parent Company                  Mill Name  \
 0            EPA MANAGEMENT SDN BHD                    SEDENAK
 1              NEW BRITAIN PALM OIL                       MOSA
 2              INTI INDOSAWIT SUBUR                   BUATAN I
 3     PAMOL ESTATES (SABAH) SDN BHD                PAMOL SABAH
 4        MUSIM MAS HOLDINGS PTE LTD               BATANG KULIM
 ...                             ...                        ...
 1679        SANLING SAWIT SEJATERA     SANLING SAWIT SEJATERA
 1680          PT CITRA AGRO KENCANA    CITRA AGRO KENCANA MILL
 1681                     ARSI GROUP     ARSI GRIYA PLANTATIONS
 1682            BUKIT JEJER SUKSES         BUKIT JEJER SUKSES
 1683      YUNI BERSAUDARA SEJAHTERA  YUNI BERSAUDARA SEJAHTERA

              RSPO Status           RSPO Type Date RSPO Certification Status  \
 0         RSPO Certified  RSPO Certified, MB                        3/31/23
 1         RSPO Certified  RSPO Certified, IP                        3/31/23
 2         RSPO Certified  RSPO Certified, MB                        3/31/23
 3         RSPO Certified  RSPO Certified, IP                        3/31/23
 4         RSPO Certified  RSPO Certified, IP                        3/31/23
 ...                  ...                 ...                            ...
 1679  Not RSPO Certified                 NaN                        3/31/23
 1680  Not RSPO Certified                 NaN                        3/31/23
 1681  Not RSPO Certified                 NaN                        3/31/23
 1682  Not RSPO Certified                 NaN                        3/31/23
 1683  Not RSPO Certified                 NaN                        3/31/23

       Latitude  Longitude  ... treeloss_ha_2021 treeloss_km_2022  \
 0         1.73     103.54  ...           321.48             1.63
 1        -5.62     150.24  ...           820.62             7.76
 2         0.43     101.82  ...           112.95             1.00
 3         6.00     117.40  ...           265.32             4.37
 4         0.08     102.03  ...           511.47             9.88
 ...        ...        ...  ...              ...              ...
 1679     -0.38     102.16  ...           104.67             0.75
 1680     -0.47     115.59  ...          3045.69            23.53
 1681     -2.86     104.94  ...            97.83             0.38
 1682     -2.29     121.79  ...           659.52            11.66
 1683     -0.03     101.19  ...          3695.49            40.01

      treeloss_ha_2022 sum_of_treeloss_km treeloss_sum_proportion_of_forest  \
 0              162.72              94.74                              0.74
 1              775.80             119.11                              0.07
 2               99.72              51.22                              0.64
 3              436.59             238.78                              0.77
 4              987.75             226.85                              0.84
 ...               ...                ...                               ...
 1679            74.52              45.40                              0.63
 1680          2353.32            1199.13                              0.29
 1681            37.62              45.72                              0.88
 1682          1166.04             251.21                              0.15
 1683          4000.59             667.27                              0.27

      remaining_forest_km remaining_proportion_of_forest  \
 0                  32.73                           0.26
 1                1666.81                           0.93
 2                  29.00                           0.36
 3                  69.49                           0.23
 4                  42.36                           0.16
 ...                  ...                            ...
 1679               26.20                           0.37
 1680             2976.48                           0.71
 1681                6.05                           0.12
 1682             1406.25                           0.85
 1683             1782.05                           0.73

       Current Deforestation Score  Past Deforestation Score  Future Risk Score
 0                               3                         4                  3
 1                               2                         1                  3
 2                               3                         4                  3
 3                               3                         4                  2
 4                               4                         5                  3
 ...                           ...                       ...                ...
 1679                            3                         3                  3
 1680                            2                         2                  3
 1681                            3                         5                  2
 1682                            2                         1                  3
 1683                            3                         2                  3

 [1684 rows x 73 columns],
 'Ferrero':            UML ID                years               Group Name  \
 0    PO1000000017            2019,2021                AGROPALMA
 1    PO1000000019            2019,2020  KULIM (MALAYSIA) BERHAD
 2    PO1000000020  2020,2021,2018,2019                    NBPOL
 3    PO1000000052            2020,2021          IOI CORPORATION
 4    PO1000000053  2021,2018,2019,2020                    SIPEF
 ..            ...                  ...                      ...
 764  PO1000011306                 2021      DHARMA AGUNG WIJAYA
 765  PO1000011478                 2021                  UNKNOWN
 766  PO1000011552                 2021                  UNKNOWN
 767  PO1000011553                 2021                  UNKNOWN
 768  PO1000011916                 2020                  UNKNOWN

                          Parent Company                   Mill Name  \
 0                             AGROPALMA                         CPA
 1                EPA MANAGEMENT SDN BHD                     SEDENAK
 2                  NEW BRITAIN PALM OIL                        MOSA
 3         PAMOL ESTATES (SABAH) SDN BHD                 PAMOL SABAH
 4                    HARGY OIL PALM LTD                  HARGY MILL
 ..                                  ...                         ...
 764          PT HANUSENTRA AGRO LESTARI  PT HANUSENTRA AGRO LESTARI
 765                      SINDORA SERAYA              SINDORA SERAYA
 766              PARENTNAME IS MILLNAME  LANGKAT MAKMUR JAYA SAWITA
 767  DUPONT & LEOSK ENTERPRISES SDN BHD          GASING SAWIT ABADI
 768                NEW BRITAIN PALM OIL                    NARANGIT

             RSPO Status           RSPO Type Date RSPO Certification Status  \
 0    Not RSPO Certified                 NaN                        3/31/23
 1        RSPO Certified  RSPO Certified, MB                        3/31/23
 2        RSPO Certified  RSPO Certified, IP                        3/31/23
 3        RSPO Certified  RSPO Certified, IP                        3/31/23
 4        RSPO Certified  RSPO Certified, IP                        3/31/23
 ..                  ...                 ...                            ...
 764  Not RSPO Certified                 NaN                        3/31/23
 765  Not RSPO Certified                 NaN                        3/31/23
 766  Not RSPO Certified                 NaN                        3/31/23
 767  Not RSPO Certified                 NaN                        3/31/23
 768  Not RSPO Certified                 NaN                        3/31/23

      Latitude  Longitude  ... treeloss_ha_2021 treeloss_km_2022  \
 0       -2.25     -48.59  ...           214.92             2.11
 1        1.73     103.54  ...           321.48             1.63
 2       -5.62     150.24  ...           820.62             7.76
 3        6.00     117.40  ...           265.32             4.37
 4       -5.31     151.01  ...           640.08            14.17
 ..        ...        ...  ...              ...              ...
 764      1.18     117.90  ...            30.69             0.41
 765      1.89     100.95  ...          2146.86            26.45
 766      3.88      98.34  ...           212.76             1.90
 767     -2.56     104.77  ...          1274.85             6.16
 768     -4.36     151.95  ...          7207.11           314.43

     treeloss_ha_2022 sum_of_treeloss_km treeloss_sum_proportion_of_forest  \
 0             210.60             104.56                              0.27
 1             162.72              94.74                              0.74
 2             775.80             119.11                              0.07
 3             436.59             238.78                              0.77
 4            1416.78             100.81                              0.09
 ..               ...                ...                               ...
 764            41.22             221.14                              0.62
 765          2645.19             663.81                              0.46
 766           190.26              31.70                              0.49
 767           616.14             326.44                              0.65
 768         31443.39            1044.47                              0.22

     remaining_forest_km remaining_proportion_of_forest  \
 0                284.88                           0.73
 1                 32.73                           0.26
 2               1666.81                           0.93
 3                 69.49                           0.23
 4               1040.02                           0.91
 ..                  ...                            ...
 764              133.70                           0.38
 765              785.63                           0.54
 766               33.48                           0.51
 767              173.38                           0.35
 768             3664.61                           0.78

      Current Deforestation Score  Past Deforestation Score  Future Risk Score
 0                              2                         2                  3
 1                              3                         4                  3
 2                              2                         1                  3
 3                              3                         4                  2
 4                              3                         1                  3
 ..                           ...                       ...                ...
 764                            1                         3                  2
 765                            3                         3                  3
 766                            4                         3                  4
 767                            3                         4                  3
 768                            5                         1                  5

 [769 rows x 73 columns],
 'FrieslandCampina':             UML ID      years               Group Name  \
 0     PO1000000017  2021,2020                AGROPALMA
 1     PO1000000019  2020,2021  KULIM (MALAYSIA) BERHAD
 2     PO1000000020  2021,2020                    NBPOL
 3     PO1000000021  2020,2021       ROYAL GOLDEN EAGLE
 4     PO1000000052  2021,2020          IOI CORPORATION
 ...            ...        ...                      ...
 1316  PO1000011556  2021,2020                  UNKNOWN
 1317  PO1000011910       2020                  UNKNOWN
 1318  PO1000011918       2020                  UNKNOWN
 1319  PO1000012622       2020                  UNKNOWN
 1320  PO1000012852       2020                  UNKNOWN

                      Parent Company                  Mill Name  \
 0                         AGROPALMA                        CPA
 1            EPA MANAGEMENT SDN BHD                    SEDENAK
 2              NEW BRITAIN PALM OIL                       MOSA
 3              INTI INDOSAWIT SUBUR                   BUATAN I
 4     PAMOL ESTATES (SABAH) SDN BHD                PAMOL SABAH
 ...                             ...                        ...
 1316           MERLUNG INTI LESTARI       MERLUNG INTI LESTARI
 1317              MAHATO INTI SAWIT          MAHATO INTI SAWIT
 1318                   ASTANA ENDAH               ASTANA ENDAH
 1319                  PALMARIS RAYA              PALMARIS RAYA
 1320      YUNI BERSAUDARA SEJAHTERA  YUNI BERSAUDARA SEJAHTERA

              RSPO Status           RSPO Type Date RSPO Certification Status  \
 0     Not RSPO Certified                 NaN                        3/31/23
 1         RSPO Certified  RSPO Certified, MB                        3/31/23
 2         RSPO Certified  RSPO Certified, IP                        3/31/23
 3         RSPO Certified  RSPO Certified, MB                        3/31/23
 4         RSPO Certified  RSPO Certified, IP                        3/31/23
 ...                  ...                 ...                            ...
 1316  Not RSPO Certified                 NaN                        3/31/23
 1317  Not RSPO Certified                 NaN                        3/31/23
 1318  Not RSPO Certified                 NaN                        3/31/23
 1319  Not RSPO Certified                 NaN                        3/31/23
 1320  Not RSPO Certified                 NaN                        3/31/23

       Latitude  Longitude  ... treeloss_ha_2021 treeloss_km_2022  \
 0        -2.25     -48.59  ...           214.92             2.11
 1         1.73     103.54  ...           321.48             1.63
 2        -5.62     150.24  ...           820.62             7.76
 3         0.43     101.82  ...           112.95             1.00
 4         6.00     117.40  ...           265.32             4.37
 ...        ...        ...  ...              ...              ...
 1316     -1.33     103.27  ...            98.91             1.03
 1317      1.37     100.30  ...            53.19             0.32
 1318      4.19     100.81  ...           288.90             2.14
 1319      0.44      99.26  ...           734.85             8.44
 1320     -0.03     101.19  ...          3695.49            40.01

      treeloss_ha_2022 sum_of_treeloss_km treeloss_sum_proportion_of_forest  \
 0              210.60             104.56                              0.27
 1              162.72              94.74                              0.74
 2              775.80             119.11                              0.07
 3               99.72              51.22                              0.64
 4              436.59             238.78                              0.77
 ...               ...                ...                               ...
 1316           102.69              48.02                              0.77
 1317            32.22               6.56                              0.52
 1318           213.57              33.69                              0.73
 1319           844.02             263.23                              0.76
 1320          4000.59             667.27                              0.27

      remaining_forest_km remaining_proportion_of_forest  \
 0                 284.88                           0.73
 1                  32.73                           0.26
 2                1666.81                           0.93
 3                  29.00                           0.36
 4                  69.49                           0.23
 ...                  ...                            ...
 1316               14.11                           0.23
 1317                6.05                           0.48
 1318               12.24                           0.27
 1319               83.54                           0.24
 1320             1782.05                           0.73

       Current Deforestation Score  Past Deforestation Score  Future Risk Score
 0                               2                         2                  3
 1                               3                         4                  3
 2                               2                         1                  3
 3                               3                         4                  3
 4                               3                         4                  2
 ...                           ...                       ...                ...
 1316                            3                         4                  3
 1317                            4                         3                  4
 1318                            5                         4                  4
 1319                            3                         4                  3
 1320                            3                         2                  3

 [1321 rows x 73 columns],
 'General Mills':             UML ID      years               Group Name  \
 0     PO1000000017  2021,2020                AGROPALMA
 1     PO1000000019  2021,2020  KULIM (MALAYSIA) BERHAD
 2     PO1000000020  2021,2020                    NBPOL
 3     PO1000000021  2021,2020       ROYAL GOLDEN EAGLE
 4     PO1000000052  2021,2020          IOI CORPORATION
 ...            ...        ...                      ...
 1737  PO1000012846       2021                  UNKNOWN
 1738  PO1000012848  2021,2020                  UNKNOWN
 1739  PO1000012849       2021                  UNKNOWN
 1740  PO1000012851       2021                  UNKNOWN
 1741  PO1000012852       2021                  UNKNOWN

                      Parent Company                  Mill Name  \
 0                         AGROPALMA                        CPA
 1            EPA MANAGEMENT SDN BHD                    SEDENAK
 2              NEW BRITAIN PALM OIL                       MOSA
 3              INTI INDOSAWIT SUBUR                   BUATAN I
 4     PAMOL ESTATES (SABAH) SDN BHD                PAMOL SABAH
 ...                             ...                        ...
 1737          PT CITRA AGRO KENCANA    CITRA AGRO KENCANA MILL
 1738                     ARSI GROUP     ARSI GRIYA PLANTATIONS
 1739            PALMA BUMI LESTARI         PALMA BUMI LESTARI
 1740            BUKIT JEJER SUKSES         BUKIT JEJER SUKSES
 1741      YUNI BERSAUDARA SEJAHTERA  YUNI BERSAUDARA SEJAHTERA

              RSPO Status           RSPO Type Date RSPO Certification Status  \
 0     Not RSPO Certified                 NaN                        3/31/23
 1         RSPO Certified  RSPO Certified, MB                        3/31/23
 2         RSPO Certified  RSPO Certified, IP                        3/31/23
 3         RSPO Certified  RSPO Certified, MB                        3/31/23
 4         RSPO Certified  RSPO Certified, IP                        3/31/23
 ...                  ...                 ...                            ...
 1737  Not RSPO Certified                 NaN                        3/31/23
 1738  Not RSPO Certified                 NaN                        3/31/23
 1739  Not RSPO Certified                 NaN                        3/31/23
 1740  Not RSPO Certified                 NaN                        3/31/23

In [138]:
# Visualize the colgate dataframe as an example
companies["Colgate"].head(25)

,UML ID,years,Group Name,Parent Company,Mill Name,RSPO Status,RSPO Type,Date RSPO Certification Status,Latitude,Longitude,...,treeloss_ha_2021,treeloss_km_2022,treeloss_ha_2022,sum_of_treeloss_km,treeloss_sum_proportion_of_forest,remaining_forest_km,remaining_proportion_of_forest,Current Deforestation Score,Past Deforestation Score,Future Risk Score
0,PO1000000019,"2021,2020,2019,2018,2017",KULIM (MALAYSIA) BERHAD,EPA MANAGEMENT SDN BHD,SEDENAK,RSPO Certified,"RSPO Certified, MB",3/31/23,1.73,103.54,...,321.48,1.63,162.72,94.74,0.74,32.73,0.26,3,4,3
1,PO1000000020,2018,NBPOL,NEW BRITAIN PALM OIL,MOSA,RSPO Certified,"RSPO Certified, IP",3/31/23,-5.62,150.24,...,820.62,7.76,775.80,119.11,0.07,1666.81,0.93,2,1,3
2,PO1000000021,"2018,2017,2020,2021,2019",ROYAL GOLDEN EAGLE,INTI INDOSAWIT SUBUR,BUATAN I,RSPO Certified,"RSPO Certified, MB",3/31/23,0.43,101.82,...,112.95,1.00,99.72,51.22,0.64,29.00,0.36,3,4,3
3,PO1000000052,"2021,2019,2018,2020",IOI CORPORATION,PAMOL ESTATES (SABAH) SDN BHD,PAMOL SABAH,RSPO Certified,"RSPO Certified, IP",3/31/23,6.00,117.40,...,265.32,4.37,436.59,238.78,0.77,69.49,0.23,3,4,2
4,PO1000000054,"2021,2019,2017,2018",MUSIM MAS,MUSIM MAS HOLDINGS PTE LTD,BATANG KULIM,RSPO Certified,"RSPO Certified, IP",3/31/23,0.08,102.03,...,511.47,9.88,987.75,226.85,0.84,42.36,0.16,4,5,3
5,PO1000000058,"2017,2018,2020,2019,2021",CARGILL,HINDOLI,SUNGAI LILIN,RSPO Certified,"RSPO Certified, IP",3/31/23,-2.61,104.13,...,161.01,2.63,263.07,49.68,0.72,19.19,0.28,4,4,3
6,PO1000000063,"2019,2020,2018,2017",SIME DARBY,SIME DARBY PLANTATION BHD,BINUANG (SOU 28),RSPO Certified,"RSPO Certified, IP",3/31/23,4.70,118.06,...,261.54,2.49,248.85,103.19,0.49,108.35,0.51,3,3,3
7,PO1000000064,"2018,2017,2019,2020",SIME DARBY,SIME DARBY PLANTATION BHD,MEROTAI (SOU 30),RSPO Certified,"RSPO Certified, MB",3/31/23,4.37,117.83,...,1237.95,12.48,1248.03,144.00,0.30,334.64,0.70,4,2,4
8,PO1000000065,"2020,2018,2019",SIME DARBY,SIME DARBY PLANTATION BHD,SANDAKAN BAY (SOU 26),RSPO Certified,"RSPO Certified, MB",3/31/23,5.64,118.17,...,931.23,7.61,760.68,137.38,0.43,180.24,0.57,4,3,4
9,PO1000000066,"2019,2017,2018",WILMAR GROUP,SABAHMAS PLANTATION SDN BHD,SABAHMAS,RSPO Certified,"RSPO Certified, MB",3/31/23,5.18,118.41,...,953.46,2.10,210.33,89.29,1.00,0.00,0.00,5,5,3
10,PO1000000091,"2017,2018,2020,2021,2019",WILMAR GROUP,SAREMAS SDN BHD,SAREMAS 1,RSPO Certified,"RSPO Certified, MB",3/31/23,3.52,113.74,...,44.10,0.69,68.76,117.32,1.00,0.38,0.00,2,5,1
11,PO1000000092,2019,MUSIM MAS,AGRO WIRATAMA,AGROWIRATAMA,RSPO Certified,"RSPO Certified, IP",3/31/23,0.20,99.63,...,1883.88,7.98,798.03,231.50,0.77,70.72,0.23,5,4,3
12,PO1000000093,"2019,2021,2017,2018,2020",WILMAR GROUP,SAREMAS SDN BHD,SAREMAS 2,RSPO Certified,"RSPO Certified, IP",3/31/23,3.45,113.77,...,1879.11,6.09,609.21,142.53,0.89,17.04,0.11,5,5,4
13,PO1000000094,"2021,2020,2019,2018,2017",IOI CORPORATION,IOI CORPORATION BHD,GOMALI,RSPO Certified,"RSPO Certified, IP",3/31/23,2.61,102.68,...,304.47,3.75,374.76,138.82,0.91,12.92,0.09,3,5,2
14,PO1000000095,"2018,2017,2021,2020,2019",SIPEF,EASTERN SUMATERA INDONESIA,BUKIT MARADJA,RSPO Certified,"RSPO Certified, IP",3/31/23,3.01,99.24,...,76.95,0.99,98.55,29.64,0.83,6.23,0.17,4,5,3
15,PO1000000097,"2019,2018,2020,2021",SIME DARBY,SIME DARBY PLANTATION BHD,EAST (SOU 8),RSPO Certified,"RSPO Certified, IP",3/31/23,2.88,101.44,...,232.29,1.11,111.24,39.13,0.53,35.34,0.47,3,3,3
16,PO1000000098,"2020,2021,2019,2018",SIME DARBY,SIME DARBY PLANTATION BHD,TANAH MERAH (SOU 14),RSPO Certified,"RSPO Certified, IP",3/31/23,2.66,101.79,...,293.13,3.12,312.48,94.51,0.88,13.30,0.12,4,5,3
17,PO1000000099,"2017,2018,2020,2021,2019",SIPEF,TOLAN TIGA INDONESIA,PERLABIAN,RSPO Certified,"RSPO Certified, IP",3/31/23,2.06,100.08,...,103.50,3.04,303.75,72.95,0.65,38.60,0.35,3,4,3
18,PO1000000103,"2019,2017,2018,2020,2021",SIME DARBY,SIME DARBY PLANTATION BHD,WEST (SOU 9),RSPO Certified,"RSPO Certified, IP",3/31/23,2.90,101.36,...,352.98,3.05,304.74,91.24,0.46,105.26,0.54,3,3,3
19,PO1000000104,"2020,2021,2019,2018,2017",SIME DARBY,SIME DARBY PLANTATION BHD,SUNGAI DINGIN (SOU 1),RSPO Certified,"RSPO Certified, MB",3/31/23,5.39,100.71,...,541.89,5.81,580.86,103.95,0.30,243.83,0.70,3,2,3
20,PO1000000106,2019,MUSIM MAS,SUKAJADI SAWIT MEKAR,SUKAJADI SAWIT MEKAR 1,RSPO Certified,"RSPO Certified, IP",3/31/23,-2.38,112.54,...,171.81,1.83,182.61,160.69,1.00,0.38,0.00,3,5,1
21,PO1000000107,"2019,2020,2021,2017,2018",SIME DARBY,SIME INDO AGRO,BUKIT AJONG,RSPO Certified,"RSPO Certified, MB",3/31/23,0.27,110.48,...,2362.68,9.24,923.85,294.65,0.70,129.06,0.30,5,4,3
22,PO1000000109,"2017,2018,2019,2020,2021",IOI CORPORATION,IOI CORPORATION BHD,PAMOL KLUANG,RSPO Certified,"RSPO Certified, IP",3/31/23,2.11,103.39,...,424.89,1.79,179.01,117.25,0.81,27.48,0.19,3,5,3
23,PO1000000110,"2020,2018,2017,2021,2019",IOI CORPORATION,IOI CORPORATION BHD,SAKILAN,RSPO Certified,"RSPO Certified, IP",3/31/23,5.84,117.84,...,181.89,2.13,213.48,48.16,0.55,39.20,0.45,3,3,3
24,PO1000000118,"2019,2021,2020,2017,2018",IOI CORPORATION,IOI CORPORATION BHD,BATURONG,RSPO Certified,"RSPO Certified, IP",3/31/23,4.76,118.09,...,121.68,3.89,389.25,63.29,0.98,1.36,0.02,5,5,3

In [139]:
companies["Colgate"].columns

Index(['UML ID', 'years', 'Group Name', 'Parent Company', 'Mill Name',
       'RSPO Status', 'RSPO Type', 'Date RSPO Certification Status',
       'Latitude', 'Longitude', 'GPS coordinates', 'ISO', 'Country',
       'Province', 'District', 'Confidence level', 'Alternative name',
       'km_forest_area_00', 'ha_forest_area_00', 'km_area', 'km_0', 'ha_0',
       'treeloss_km_2001', 'treeloss_ha_2001', 'treeloss_km_2002',
       'treeloss_ha_2002', 'treeloss_km_2003', 'treeloss_ha_2003',
       'treeloss_km_2004', 'treeloss_ha_2004', 'treeloss_km_2005',
       'treeloss_ha_2005', 'treeloss_km_2006', 'treeloss_ha_2006',
       'treeloss_km_2007', 'treeloss_ha_2007', 'treeloss_km_2008',
       'treeloss_ha_2008', 'treeloss_km_2009', 'treeloss_ha_2009',
       'treeloss_km_2010', 'treeloss_ha_2010', 'treeloss_km_2011',
       'treeloss_ha_2011', 'treeloss_km_2012', 'treeloss_ha_2012',
       'treeloss_km_2013', 'treeloss_ha_2013', 'treeloss_km_2014',
       'treeloss_ha_2014', 'treeloss_km_2015', 'treeloss_ha_2015',
       'treeloss_km_2016', 'treeloss_ha_2016', 'treeloss_km_2017',
       'treeloss_ha_2017', 'treeloss_km_2018', 'treeloss_ha_2018',
       'treeloss_km_2019', 'treeloss_ha_2019', 'treeloss_km_2020',
       'treeloss_ha_2020', 'treeloss_km_2021', 'treeloss_ha_2021',
       'treeloss_km_2022', 'treeloss_ha_2022', 'sum_of_treeloss_km',
       'treeloss_sum_proportion_of_forest', 'remaining_forest_km',
       'remaining_proportion_of_forest', 'Current Deforestation Score',
       'Past Deforestation Score', 'Future Risk Score'],
      dtype='object')

In [159]:
# Clean the dataframes and only save the rows with Sumatra provinces
def prepare_df(df):

  """
  Create a dataframe with only information of Sumatra, Indonesia
  """

  # Save data from Sumatra in specific (cut the rest of the columns and rows)
  df = df[df["Province"].isin(provinces)]

  # Save the columns we consider important
  df = df.loc[:, "UML ID":"sum_of_treeloss_km"].reset_index()
  df.drop(columns = df.loc[:, "Confidence level" : "treeloss_ha_2022"], inplace = True)

  # Sort data by province and parent company columns
  df_prov = df.loc[:, ["Province", "Parent Company", "RSPO Status", "sum_of_treeloss_km"]].sort_values(by = ["Province", "Parent Company"])
  df_prov = df_prov.groupby(["Province", "Parent Company", "RSPO Status"])["sum_of_treeloss_km"].sum()

  return df_prov.reset_index()

In [160]:
# Prepare the dataframe for each company
for company in companies:

    company_df = companies[company] # Dataframe
    companies[company] = prepare_df(company_df) # Edit dataframe

In [162]:
# Visualize the Colgate dataframe
companies["Colgate"]

,Province,Parent Company,RSPO Status,sum_of_treeloss_km
0,Aceh,ANUGRAH FAJAR REZEKI,Not RSPO Certified,85.64
1,Aceh,BANGUN SEMPURNA LESTARI,Not RSPO Certified,397.91
2,Aceh,BEURATA SUBUR PERSADA,Not RSPO Certified,278.23
3,Aceh,BLANG KETUMBA,Not RSPO Certified,494.62
4,Aceh,BOSWA MEGALOPOLIS,Not RSPO Certified,527.55
...,...,...,...,...
551,Sumatera Utara,UMBUL MAS WISESA,RSPO Certified,197.00
552,Sumatera Utara,UNITED KINGDOM INDONESIA PLANTATION,Not RSPO Certified,26.22
553,Sumatera Utara,VAREM SAWIT CEMERLANG,Not RSPO Certified,92.82
554,Sumatera Utara,VICTORINDO ALAM LESTARI,Not RSPO Certified,321.54
555,Sumatera Utara,YAPUTRA ALFA PALMINDO,Not RSPO Certified,14.09

In [163]:
# Count the amount of mills the company has in each Sumatra province
def mill_quantity(company_list):

  """
  This function takes the list of all the company dataframes and calculates the amount
  of mills they posses in each region and the amount of tree loss they've caused.

  Returns a dataframe with the information calculated.
  """

  # Create dataframe
  mill_info = pd.DataFrame()

  # Iterate through the company dataframes and provinces
  for company in companies:
    for p in provinces:

      # Temporary df with information of a specific province
      temp = companies[company["Province"] == p]
      print(temp)

In [164]:
# Dictionary with mill information
mill_info = {}

# Iterate through the company dataframes and provinces
for company in companies:
  for p in provinces:
    
    # Temporary df with information of a specific province
    specific_company = companies[company]
    temp = specific_company[specific_company["Province"] == p]
    print(temp)

temp

   Province                  Parent Company         RSPO Status  \
0      Aceh            ANUGRAH FAJAR REZEKI  Not RSPO Certified
1      Aceh         BANGUN SEMPURNA LESTARI  Not RSPO Certified
2      Aceh           BEURATA SUBUR PERSADA  Not RSPO Certified
3      Aceh                   BLANG KETUMBA  Not RSPO Certified
4      Aceh               BOSWA MEGALOPOLIS  Not RSPO Certified
5      Aceh             BUMI DAYA AGROTAMAS  Not RSPO Certified
6      Aceh                 BUMI SAMA GANDA  Not RSPO Certified
7      Aceh                   DELIMA MAKMUR  Not RSPO Certified
8      Aceh                   ENSEM LESTARI  Not RSPO Certified
9      Aceh                    ENSEM SAWITA  Not RSPO Certified
10     Aceh        FAJAR BAIZURI & BROTHERS  Not RSPO Certified
11     Aceh               KARYA TANAH SUBUR  Not RSPO Certified
12     Aceh             KOPERASI PRIMA JASA  Not RSPO Certified
13     Aceh                     MOPOLI RAYA  Not RSPO Certified
14     Aceh           MUTIARA SAWIT LESTARI  Not RSPO Certified
15     Aceh                       NAFASINDO  Not RSPO Certified
16     Aceh                      PARASAWITA  Not RSPO Certified
17     Aceh             PERKASA SUBUR SAKTI      RSPO Certified
18     Aceh        PERKEBUNAN LEMBAH BHAKTI  Not RSPO Certified
19     Aceh          PERKEBUNAN NUSANTARA I  Not RSPO Certified
20     Aceh          PERKEBUNAN NUSANTARA I      RSPO Certified
21     Aceh  PERKEBUNAN PERTANIAN PATI SARI  Not RSPO Certified
22     Aceh                      RAJA MARGA  Not RSPO Certified
23     Aceh           SAMUDERA SAWIT NABATI  Not RSPO Certified
24     Aceh         SAWIT NAGAN RAYA MAKMUR  Not RSPO Certified
25     Aceh        SINGKIL SEJAHTERA MAKMUR  Not RSPO Certified
26     Aceh                         SISIRAU  Not RSPO Certified
27     Aceh                SOCFIN INDONESIA      RSPO Certified
28     Aceh               SURYA PANEN SUBUR  Not RSPO Certified
29     Aceh                   SYAUKATH AGRO  Not RSPO Certified
30     Aceh              SYAUKATH SEJAHTERA  Not RSPO Certified
31     Aceh                     TEUPIN LADA  Not RSPO Certified
32     Aceh          TRI AGRO PALMA TAMIANG  Not RSPO Certified
33     Aceh              UJONG NEUBOK DALAM  Not RSPO Certified
34     Aceh                         UNKNOWN  Not RSPO Certified

    sum_of_treeloss_km
0                85.64
1               397.91
2               278.23
3               494.62
4               527.55
5               140.24
6                 8.47
7                31.71
8               157.94
9                79.56
10               28.96
11              576.14
12               46.12
13              299.50
14               82.70
15              158.65
16               39.32
17              120.02
18              131.84
19              349.02
20              166.12
21              128.53
22               40.13
23              246.52
24               72.42
25              225.37
26               19.54
27              457.06
28              125.88
29                1.57
30              200.68
31               60.82
32               44.48
33               20.65
34              146.20
    Province                Parent Company         RSPO Status  \
141     Riau  ADEI PLANTATION AND INDUSTRY      RSPO Certified
142     Riau          ADIMULIA AGROLESTARI  Not RSPO Certified
143     Riau                    AGRO ABADI  Not RSPO Certified
144     Riau        AGRO SARIMAS INDONESIA  Not RSPO Certified
145     Riau                AGRO SEJAHTERA  Not RSPO Certified
..       ...                           ...                 ...
319     Riau                       UNKNOWN  Not RSPO Certified
320     Riau             USAHA KITA MAKMUR  Not RSPO Certified
321     Riau             WANA JINGGA TIMUR  Not RSPO Certified
322     Riau            WANASARI NUSANTARA  Not RSPO Certified
323     Riau     YUNI BERSAUDARA SEJAHTERA  Not RSPO Certified

     sum_of_treeloss_km
141             1917.44
142              110.61
143              179.22
144             1505.44
145               66.20
..                  ...
319               48.46
320              203.95
321              234.50
322               86.78
323              667.27

[183 rows x 4 columns]
    Province            Parent Company         RSPO Status  sum_of_treeloss_km
35  Bengkulu            AGRA SAWITINDO  Not RSPO Certified              349.84
36  Bengkulu              AGRI ANDALAS  Not RSPO Certified               86.07
37  Bengkulu                 AGRICINAL  Not RSPO Certified               58.30
38  Bengkulu     AGRINDO INDAH PERSADA  Not RSPO Certified              282.04
39  Bengkulu                 AGRO MUKO      RSPO Certified              119.66
40  Bengkulu           ALNO AGRO UTAMA  Not RSPO Certified              211.61
41  Bengkulu   ANUGERAH PELANGI SUKSES  Not RSPO Certified              366.36
42  Bengkulu    BENGKULU SAWIT LESTARI  Not RSPO Certified              162.15
43  Bengkulu   BIO NUSANTARA TEKNOLOGI  Not RSPO Certified              107.73
44  Bengkulu        BUMI MENTARI KARYA  Not RSPO Certified               59.71
45  Bengkulu      CAHAYA SAWIT LESTARI  Not RSPO Certified               88.29
46  Bengkulu      CIPTAMAS BUMISELARAS  Not RSPO Certified              527.71
47  Bengkulu      DARIA DHARMA PRATAMA  Not RSPO Certified              385.29
48  Bengkulu      KARYA AGRO SAWITINDO  Not RSPO Certified               21.84
49  Bengkulu       KARYA SAWITINDO MAS  Not RSPO Certified              121.45
50  Bengkulu     KENCANA KATARA KEWALA  Not RSPO Certified              199.57
51  Bengkulu          MITRA PUDING MAS  Not RSPO Certified              161.98
52  Bengkulu   MUKO MUKO INDAH LESTARI  Not RSPO Certified               31.90
53  Bengkulu          PALMA MAS SEJATI  Not RSPO Certified               65.81
54  Bengkulu  PERKEBUNAN NUSANTARA VII  Not RSPO Certified              236.23
55  Bengkulu     SANDABI INDAH LESTARI  Not RSPO Certified              132.71
56  Bengkulu  SAPTA SENTOSA JAYA ABADI  Not RSPO Certified               68.06
57  Bengkulu               SAWIT MULIA  Not RSPO Certified              224.44
58  Bengkulu  SENTOSA SEJAHTERA SEJATI  Not RSPO Certified               16.28
59  Bengkulu    SINAR BENGKULU SELATAN  Not RSPO Certified              293.80
             Province                  Parent Company         RSPO Status  \
355  Sumatera Selatan                       AEK TARUM      RSPO Certified
356  Sumatera Selatan                     ANDIRA AGRO  Not RSPO Certified
357  Sumatera Selatan                      ARSI GROUP  Not RSPO Certified
358  Sumatera Selatan       BANYU KAHURIPAN INDONESIA  Not RSPO Certified
359  Sumatera Selatan   BANYUASIN NUSANTARA SEJAHTERA  Not RSPO Certified
..                ...                             ...                 ...
413  Sumatera Selatan                   TELAGA HIKMAH      RSPO Certified
414  Sumatera Selatan      TRANSPACIFIC AGRO INDUSTRY  Not RSPO Certified
415  Sumatera Selatan  WAHANA KARYA MANDIRI KAHURIPAN  Not RSPO Certified
416  Sumatera Selatan             WAHANA POTENSI GUNA  Not RSPO Certified
417  Sumatera Selatan              WAIMUSI AGRO INDAH  Not RSPO Certified

     sum_of_treeloss_km
355              290.05
356              504.40
357               45.72
358              160.85
359              228.86
..                  ...
413              898.95
414               96.21
415              699.95
416              172.92
417               35.96

[63 rows x 4 columns]
           Province               Parent Company         RSPO Status  \
324  Sumatera Barat            AGRO WIRA LIGATSA  Not RSPO Certified
325  Sumatera Barat                AGRO WIRATAMA      RSPO Certified
326  Sumatera Barat               AMP PLANTATION      RSPO Certified
327  Sumatera Barat        ANDALAS AGRO INDUSTRI      RSPO Certified
328  Sumatera Barat       ANDALAS WAHANA BERJAYA  Not RSPO Certified
329  Sumatera Barat   BAKRIE PASAMAN PLANTATIONS  Not RSPO Certified
330  Sumatera Barat       BERKAT SAWIT SEJAHTERA  Not RSPO Certified
331  Sumatera Barat     BINA PRATAMA SAKOTO JAYA  Not RSPO Certified
332  Sumatera Barat       BINTARA TANI NUSANTARA  Not RSPO Certified
333  Sumatera Barat          BUKIT SAWIT SEMESTA  Not RSPO Certified
334  Sumatera Barat       DHARMASRAYA LESTARINDO  Not RSPO Certified
335  Sumatera Barat    DHARMASRAYA SAWIT LESTARI  Not RSPO Certified
336  Sumatera Barat   GERSINDO MINANG PLANTATION      RSPO Certified
337  Sumatera Barat           GUNUNG SAWIT ABADI  Not RSPO Certified
338  Sumatera Barat                  INCASI RAYA  Not RSPO Certified
339  Sumatera Barat               INKUD AGRITAMA  Not RSPO Certified
340  Sumatera Barat        KEMILAU PERMATA SAWIT  Not RSPO Certified
341  Sumatera Barat      KENCANA SAWIT INDONESIA      RSPO Certified
342  Sumatera Barat                 MUTIARA AGAM  Not RSPO Certified
343  Sumatera Barat     PASAMAN MARAMA SEJAHTERA  Not RSPO Certified
344  Sumatera Barat      PERKEBUNAN NUSANTARA VI  Not RSPO Certified
345  Sumatera Barat      PERKEBUNAN NUSANTARA VI      RSPO Certified
346  Sumatera Barat       PERKEBUNAN PELALU RAYA  Not RSPO Certified
347  Sumatera Barat  RIMBO PANJANG SUMBER MAKMUR  Not RSPO Certified
348  Sumatera Barat              SARI BUAH SAWIT  Not RSPO Certified
349  Sumatera Barat          SAWITA PASAMAN JAYA  Not RSPO Certified
350  Sumatera Barat     SELAGO MAKMUR PLANTATION  Not RSPO Certified
351  Sumatera Barat   SUMATERA JAYA AGRO LESTARI  Not RSPO Certified
352  Sumatera Barat       SUMBAR ANDALAS KENCANA  Not RSPO Certified
353  Sumatera Barat          TIDAR KERINCI AGUNG  Not RSPO Certified
354  Sumatera Barat          USAHA SAWIT MANDIRI  Not RSPO Certified

     sum_of_treeloss_km
324              107.25
325              231.50
326               97.58
327               15.83
328              327.13
329              117.62
330                3.20
331               67.40
332              104.88
333              148.12
334               92.53
335              232.12
336              133.14
337               42.46
338              402.77
339              201.32
340              886.01
341              291.56
342              110.47
343               32.13
344              471.69
345              360.45
346               89.98
347                2.99
348               57.16
349              131.14
350              180.71
351              354.66
352              324.89
353              271.23
354               15.28
           Province                       Parent Company         RSPO Status  \
418  Sumatera Utara                      ABDI BUDI MULIA  Not RSPO Certified
419  Sumatera Utara                AGRINDO INDAH PERSADA  Not RSPO Certified
420  Sumatera Utara                   AGUNG AGRO LESTARI  Not RSPO Certified
421  Sumatera Utara                            AMAL TANI  Not RSPO Certified
422  Sumatera Utara              ANUGERAH LANGKAT MAKMUR  Not RSPO Certified
..              ...                                  ...                 ...
551  Sumatera Utara                     UMBUL MAS WISESA      RSPO Certified
552  Sumatera Utara  UNITED KINGDOM INDONESIA PLANTATION  Not RSPO Certified
553  Sumatera Utara                VAREM SAWIT CEMERLANG  Not RSPO Certified
554  Sumatera Utara              VICTORINDO ALAM LESTARI  Not RSPO Certified
555  Sumatera Utara                YAPUTRA ALFA PALMINDO  Not RSPO Certified

     sum_of_treeloss_km
418              686.91
419               11.18
420               99.32
421               32.39
422                9.70
..                  ...
551              197.00
552               26.22
553               92.82
554              321.54
555               14.09

[138 rows x 4 columns]
    Province            Parent Company         RSPO Status  sum_of_treeloss_km
60     Jambi    ADIMULIA PALMO LESTARI  Not RSPO Certified              100.23
61     Jambi     AGRINDO INDAH PERSADA  Not RSPO Certified              791.94
62     Jambi         AGRO MITRA MADANI      RSPO Certified              271.43
63     Jambi      AGRO WIJAYA INDUSTRI  Not RSPO Certified               64.41
64     Jambi    ANEKA PURA MULTI KERTA  Not RSPO Certified               46.64
..       ...                       ...                 ...                 ...
121    Jambi  SURYA SUMBER SAWIT ABADI  Not RSPO Certified              521.55
122    Jambi   SURYA UTAMA AGROLESTARI  Not RSPO Certified               46.76
123    Jambi                TEBO INDAH  Not RSPO Certified                5.54
124    Jambi   TEBO PLASMA INTILESTARI  Not RSPO Certified              106.76
125    Jambi          TRIMITRA LESTARI  Not RSPO Certified              540.57

[66 rows x 4 columns]
    Province            Parent Company         RSPO Status  sum_of_treeloss_km
126  Lampung             AGRO BUMI MAS  Not RSPO Certified              426.88
127  Lampung    ANAKTUHA SAWIT MANDIRI  Not RSPO Certified               11.99
128  Lampung       GARUDA BUMI PERKASA  Not RSPO Certified               35.02
129  Lampung          KALIREJO LESTARI  Not RSPO Certified              222.61
130  Lampung       KRIYA SWARNA PUBIAN  Not RSPO Certified              191.16
131  Lampung      LAMBANG BUMI PERKASA  Not RSPO Certified              140.75
132  Lampung        MENGGALA SAWITINDO  Not RSPO Certified              191.00
133  Lampung      PALM LAMPUNG PERSADA  Not RSPO Certified              201.27
134  Lampung  PERKEBUNAN NUSANTARA VII  Not RSPO Certified              357.17
135  Lampung     SINAR JAYA INTI MULYA  Not RSPO Certified               86.47
136  Lampung      SUMBER INDAH PERKASA      RSPO Certified              375.80
137  Lampung        SURYA UTAMA NABATI  Not RSPO Certified              275.74
138  Lampung        TUNAS BARU LAMPUNG  Not RSPO Certified              664.16
139  Lampung        TUNAS BARU LAMPUNG      RSPO Certified               85.03
140  Lampung    WAYKANAN SAWITINDO MAS  Not RSPO Certified              376.36
   Province                  Parent Company         RSPO Status  \
0      Aceh            ANUGRAH FAJAR REZEKI  Not RSPO Certified
1      Aceh         BANGUN SEMPURNA LESTARI  Not RSPO Certified
2      Aceh           BEURATA SUBUR PERSADA  Not RSPO Certified
3      Aceh                   BLANG KETUMBA  Not RSPO Certified
4      Aceh             BUMI DAYA AGROTAMAS  Not RSPO Certified
5      Aceh                 BUMI SAMA GANDA  Not RSPO Certified
6      Aceh                   ENSEM LESTARI  Not RSPO Certified
7      Aceh                    ENSEM SAWITA  Not RSPO Certified
8      Aceh               KARYA TANAH SUBUR  Not RSPO Certified
9      Aceh                     MOPOLI RAYA  Not RSPO Certified
10     Aceh                       NAFASINDO  Not RSPO Certified
11     Aceh                      PARASAWITA  Not RSPO Certified
12     Aceh             PERKASA SUBUR SAKTI      RSPO Certified
13     Aceh        PERKEBUNAN LEMBAH BHAKTI  Not RSPO Certified
14     Aceh          PERKEBUNAN NUSANTARA I  Not RSPO Certified
15     Aceh          PERKEBUNAN NUSANTARA I      RSPO Certified
16     Aceh  PERKEBUNAN PERTANIAN PATI SARI  Not RSPO Certified
17     Aceh                      RAJA MARGA  Not RSPO Certified
18     Aceh           SAMUDERA SAWIT NABATI  Not RSPO Certified
19     Aceh         SAWIT NAGAN RAYA MAKMUR  Not RSPO Certified
20     Aceh                SOCFIN INDONESIA      RSPO Certified
21     Aceh                   SYAUKATH AGRO  Not RSPO Certified
22     Aceh                     TEUPIN LADA  Not RSPO Certified
23     Aceh          TRI AGRO PALMA TAMIANG  Not RSPO Certified
24     Aceh                         UNKNOWN  Not RSPO Certified

    sum_of_treeloss_km
0                85.64
1               397.91
2               278.23
3               494.62
4               140.24
5                 8.47
6               157.94
7                79.56
8               576.14
9               299.50
10              158.65
11               39.32
12              120.02
13              131.84
14              349.02
15              166.12
16              128.53
17               40.13
18              246.52
19               72.42
20              457.06
21                1.57
22               60.82
23               44.48
24              146.20
    Province                Parent Company         RSPO Status  \
76      Riau  ADEI PLANTATION AND INDUSTRY      RSPO Certified
77      Riau          ADIMULIA AGROLESTARI  Not RSPO Certified
78      Riau                    AGRO ABADI  Not RSPO Certified
79      Riau  ANDIKA PERMATA SAWIT LESTARI  Not RSPO Certified
80      Riau            ANEKA INTI PERSADA      RSPO Certified
..       ...                           ...                 ...
175     Riau            TUNAS BARU LAMPUNG  Not RSPO Certified
176     Riau     TUNGGAL MITRA PLANTATIONS      RSPO Certified
177     Riau   TUNGGAL PERKASA PLANTATIONS  Not RSPO Certified
178     Riau                       UNKNOWN  Not RSPO Certified
179     Riau            WANASARI NUSANTARA  Not RSPO Certified

     sum_of_treeloss_km
76              1917.44
77               110.61
78               179.22
79               105.92
80                62.24
..                  ...
175               40.98
176              260.63
177              374.72
178               48.46
179               86.78

[104 rows x 4 columns]
    Province           Parent Company         RSPO Status  sum_of_treeloss_km
25  Bengkulu                AGRICINAL  Not RSPO Certified               58.30
26  Bengkulu                AGRO MUKO      RSPO Certified              119.66
27  Bengkulu   BENGKULU SAWIT LESTARI  Not RSPO Certified              162.15
28  Bengkulu  BIO NUSANTARA TEKNOLOGI  Not RSPO Certified              107.73
29  Bengkulu     CIPTAMAS BUMISELARAS  Not RSPO Certified              527.71
30  Bengkulu         PALMA MAS SEJATI  Not RSPO Certified               65.81
31  Bengkulu   SINAR BENGKULU SELATAN  Not RSPO Certified              293.80
             Province                      Parent Company         RSPO Status  \
187  Sumatera Selatan                           AEK TARUM      RSPO Certified
188  Sumatera Selatan                  BASTIAN OLAH SAWIT  Not RSPO Certified
189  Sumatera Selatan                 BERKAT SAWIT SEJATI      RSPO Certified
190  Sumatera Selatan               BERKAT SAWIT SUKAMAJU  Not RSPO Certified
191  Sumatera Selatan                BINA SAINS CEMERLANG      RSPO Certified
192  Sumatera Selatan                BINAKARYA ERAMANDIRI  Not RSPO Certified
193  Sumatera Selatan                   BUMI SAWIT PERMAI      RSPO Certified
194  Sumatera Selatan            CAHAYA CEMERLANG LESTARI  Not RSPO Certified
195  Sumatera Selatan                        CAMPANG TIGA  Not RSPO Certified
196  Sumatera Selatan                        CIPTA FUTURA  Not RSPO Certified
197  Sumatera Selatan           DAYA SEMESTA AGRO PERSADA  Not RSPO Certified
198  Sumatera Selatan               DJUANDA SAWIT LESTARI      RSPO Certified
199  Sumatera Selatan  DUPONT & LEOSK ENTERPRISES SDN BHD  Not RSPO Certified
200  Sumatera Selatan            GOLDEN OILINDO NUSANTARA  Not RSPO Certified
201  Sumatera Selatan                    GUNUNG TUA ABADI      RSPO Certified
202  Sumatera Selatan                             HINDOLI      RSPO Certified
203  Sumatera Selatan               KARYA INDO SEJATITAMA  Not RSPO Certified
204  Sumatera Selatan                        MINANGA OGAN  Not RSPO Certified
205  Sumatera Selatan                  MUTIARA BUNDA JAYA      RSPO Certified
206  Sumatera Selatan       PERKEBUNAN HASIL MUSI LESTARI  Not RSPO Certified
207  Sumatera Selatan            PERKEBUNAN NUSANTARA VII  Not RSPO Certified
208  Sumatera Selatan            PERKEBUNAN NUSANTARA VII      RSPO Certified
209  Sumatera Selatan                        PINAGO UTAMA  Not RSPO Certified
210  Sumatera Selatan                 SAWIT MAS SEJAHTERA  Not RSPO Certified
211  Sumatera Selatan                 SAWIT MAS SEJAHTERA      RSPO Certified
212  Sumatera Selatan                        SELAPAN JAYA      RSPO Certified

    Province            Parent Company         RSPO Status  sum_of_treeloss_km
128  Lampung    ANAKTUHA SAWIT MANDIRI  Not RSPO Certified               11.99
129  Lampung       GARUDA BUMI PERKASA  Not RSPO Certified               35.02
130  Lampung          KALIREJO LESTARI  Not RSPO Certified              222.61
131  Lampung       KRIYA SWARNA PUBIAN  Not RSPO Certified              191.16
132  Lampung      LAMBANG BUMI PERKASA  Not RSPO Certified              140.75
133  Lampung        MENGGALA SAWITINDO  Not RSPO Certified              191.00
134  Lampung      PALM LAMPUNG PERSADA  Not RSPO Certified              201.27
135  Lampung  PERKEBUNAN NUSANTARA VII  Not RSPO Certified               60.67
136  Lampung     SINAR JAYA INTI MULYA  Not RSPO Certified               86.47
137  Lampung      SUMBER INDAH PERKASA      RSPO Certified              375.80
138  Lampung        SURYA UTAMA NABATI  Not RSPO Certified              275.74
139  Lampung    WAYKANAN SAWITINDO MAS  Not RSPO Certified              376.36

In [30]:
# Calculate total colgate mills per province
colgate_mill_count = {}

for p in provinces:
  data = {"Mill Count": 0, "Treeloss km": 0}
  temp = colgate_pmill[colgate_pmill["Province"] == p]
  data["Mill Count"] = temp["Parent Company"].nunique()
  data["Treeloss km"] = temp["sum_of_treeloss_km"].sum()
  colgate_mill_count[p] = data

colgate_mill_count

{'Aceh': {'Mill Count': 34, 'Treeloss km': 5990.11},
 'Riau': {'Mill Count': 177, 'Treeloss km': 44379.99},
 'Bengkulu': {'Mill Count': 25, 'Treeloss km': 4378.83},
 'Sumatera Selatan': {'Mill Count': 61, 'Treeloss km': 26717.66},
 'Sumatera Barat': {'Mill Count': 30, 'Treeloss km': 5905.2},
 'Sumatera Utara': {'Mill Count': 134, 'Treeloss km': 16137.759999999998},
 'Jambi': {'Mill Count': 64, 'Treeloss km': 18600.66},
 'Lampung': {'Mill Count': 14, 'Treeloss km': 3641.4100000000003}}