In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import os

In [2]:
# Provinces in Indonesia list
provinces = ["Aceh", "Riau", "Bengkulu", "Sumatera Selatan", "Sumatera Barat", "Sumatera Utara", "Jambi", "Lampung"]

In [3]:
# Get csv files with company information

# Change directory to access all csv files
cwd = os.getcwd() # Get current working directory
list_cwd = os.listdir() # List all files and directories inside the present one
os.chdir(cwd + "\\" + list_cwd[1]) # Change directory to the one with the csv's

# Get all csvs
companies_list = os.listdir()
companies_list

['Colgate-Palmolive-Mill-Owners-2026-7-27.csv',
 'Colgate-Palmolive-Mills-2026-7-27.csv',
 'Ferrero-Mill-Owners-2026-7-27.csv',
 'Ferrero-Mills-2026-7-27.csv',
 'FrieslandCampina-Mills-2026-7-28.csv',
 'General Mills-Mills-2026-7-28.csv',
 'Hershey-Mills-2026-7-28.csv',
 'Johnson & Johnson-Mill-Owners-2026-7-27.csv',
 'Johnson & Johnson-Mills-2026-7-27.csv',
 'Kellogg-Mills-2026-7-28.csv',
 'L_OREAL-Mill-Owners-2026-7-27.csv',
 'L_OREAL-Mills-2026-7-27.csv',
 'Mars-Mills-2026-7-28.csv',
 'Mondelez-Mills-2026-7-28.csv',
 'Nestle-Mills-2026-7-28.csv',
 'PepsiCo-Mills-2026-7-28.csv',
 'Procter & Gamble-Mills-2026-7-28.csv',
 'Reckitt Benckiser (RB)-Mills-2026-7-28.csv',
 'Unilever-Mills-2026-7-28.csv']

In [31]:
# Dictionary for company dataframe information
companies = {}

# Save the company name and the dataframe
for company in companies_list:

    name = company.split("-")[0] # Get the first word of the file name
    companies[name] = pd.read_csv(company) # Save csv as dataframe

# Example to visualize what's in the dictionary  
companies

{'Colgate':             UML ID                     years               Group Name  \
 0     PO1000000019  2021,2020,2019,2018,2017  KULIM (MALAYSIA) BERHAD
 1     PO1000000020                      2018                    NBPOL
 2     PO1000000021  2018,2017,2020,2021,2019       ROYAL GOLDEN EAGLE
 3     PO1000000052       2021,2019,2018,2020          IOI CORPORATION
 4     PO1000000054       2021,2019,2017,2018                MUSIM MAS
 ...            ...                       ...                      ...
 1679  PO1000012845                      2021                  UNKNOWN
 1680  PO1000012846                      2021                  UNKNOWN
 1681  PO1000012848            2021,2019,2020                  UNKNOWN
 1682  PO1000012851                      2021                  UNKNOWN
 1683  PO1000012852                      2021                  UNKNOWN

                      Parent Company                  Mill Name  \
 0            EPA MANAGEMENT SDN BHD                    SEDENAK
 1              NEW BRITAIN PALM OIL                       MOSA
 2              INTI INDOSAWIT SUBUR                   BUATAN I
 3     PAMOL ESTATES (SABAH) SDN BHD                PAMOL SABAH
 4        MUSIM MAS HOLDINGS PTE LTD               BATANG KULIM
 ...                             ...                        ...
 1679        SANLING SAWIT SEJATERA     SANLING SAWIT SEJATERA
 1680          PT CITRA AGRO KENCANA    CITRA AGRO KENCANA MILL
 1681                     ARSI GROUP     ARSI GRIYA PLANTATIONS
 1682            BUKIT JEJER SUKSES         BUKIT JEJER SUKSES
 1683      YUNI BERSAUDARA SEJAHTERA  YUNI BERSAUDARA SEJAHTERA

              RSPO Status           RSPO Type Date RSPO Certification Status  \
 0         RSPO Certified  RSPO Certified, MB                        3/31/23
 1         RSPO Certified  RSPO Certified, IP                        3/31/23
 2         RSPO Certified  RSPO Certified, MB                        3/31/23
 3         RSPO Certified  RSPO Certified, IP                        3/31/23
 4         RSPO Certified  RSPO Certified, IP                        3/31/23
 ...                  ...                 ...                            ...
 1679  Not RSPO Certified                 NaN                        3/31/23
 1680  Not RSPO Certified                 NaN                        3/31/23
 1681  Not RSPO Certified                 NaN                        3/31/23
 1682  Not RSPO Certified                 NaN                        3/31/23
 1683  Not RSPO Certified                 NaN                        3/31/23

       Latitude  Longitude  ... treeloss_ha_2021 treeloss_km_2022  \
 0         1.73     103.54  ...           321.48             1.63
 1        -5.62     150.24  ...           820.62             7.76
 2         0.43     101.82  ...           112.95             1.00
 3         6.00     117.40  ...           265.32             4.37
 4         0.08     102.03  ...           511.47             9.88
 ...        ...        ...  ...              ...              ...
 1679     -0.38     102.16  ...           104.67             0.75
 1680     -0.47     115.59  ...          3045.69            23.53
 1681     -2.86     104.94  ...            97.83             0.38
 1682     -2.29     121.79  ...           659.52            11.66
 1683     -0.03     101.19  ...          3695.49            40.01

      treeloss_ha_2022 sum_of_treeloss_km treeloss_sum_proportion_of_forest  \
 0              162.72              94.74                              0.74
 1              775.80             119.11                              0.07
 2               99.72              51.22                              0.64
 3              436.59             238.78                              0.77
 4              987.75             226.85                              0.84
 ...               ...                ...                               ...
 1679            74.52              45.40                              0.63
 1680          2353.32            1199.13                              0.29
 1681            37.62              45.72                              0.88
 1682          1166.04             251.21                              0.15
 1683          4000.59             667.27                              0.27

      remaining_forest_km remaining_proportion_of_forest  \
 0                  32.73                           0.26
 1                1666.81                           0.93
 2                  29.00                           0.36
 3                  69.49                           0.23
 4                  42.36                           0.16
 ...                  ...                            ...
 1679               26.20                           0.37
 1680             2976.48                           0.71
 1681                6.05                           0.12
 1682             1406.25                           0.85
 1683             1782.05                           0.73

       Current Deforestation Score  Past Deforestation Score  Future Risk Score
 0                               3                         4                  3
 1                               2                         1                  3
 2                               3                         4                  3
 3                               3                         4                  2
 4                               4                         5                  3
 ...                           ...                       ...                ...
 1679                            3                         3                  3
 1680                            2                         2                  3
 1681                            3                         5                  2
 1682                            2                         1                  3
 1683                            3                         2                  3

 [1684 rows x 73 columns],
 'Ferrero':            UML ID                years               Group Name  \
 0    PO1000000017            2019,2021                AGROPALMA
 1    PO1000000019            2019,2020  KULIM (MALAYSIA) BERHAD
 2    PO1000000020  2020,2021,2018,2019                    NBPOL
 3    PO1000000052            2020,2021          IOI CORPORATION
 4    PO1000000053  2021,2018,2019,2020                    SIPEF
 ..            ...                  ...                      ...
 764  PO1000011306                 2021      DHARMA AGUNG WIJAYA
 765  PO1000011478                 2021                  UNKNOWN
 766  PO1000011552                 2021                  UNKNOWN
 767  PO1000011553                 2021                  UNKNOWN
 768  PO1000011916                 2020                  UNKNOWN

                          Parent Company                   Mill Name  \
 0                             AGROPALMA                         CPA
 1                EPA MANAGEMENT SDN BHD                     SEDENAK
 2                  NEW BRITAIN PALM OIL                        MOSA
 3         PAMOL ESTATES (SABAH) SDN BHD                 PAMOL SABAH
 4                    HARGY OIL PALM LTD                  HARGY MILL
 ..                                  ...                         ...
 764          PT HANUSENTRA AGRO LESTARI  PT HANUSENTRA AGRO LESTARI
 765                      SINDORA SERAYA              SINDORA SERAYA
 766              PARENTNAME IS MILLNAME  LANGKAT MAKMUR JAYA SAWITA
 767  DUPONT & LEOSK ENTERPRISES SDN BHD          GASING SAWIT ABADI
 768                NEW BRITAIN PALM OIL                    NARANGIT

             RSPO Status           RSPO Type Date RSPO Certification Status  \
 0    Not RSPO Certified                 NaN                        3/31/23
 1        RSPO Certified  RSPO Certified, MB                        3/31/23
 2        RSPO Certified  RSPO Certified, IP                        3/31/23
 3        RSPO Certified  RSPO Certified, IP                        3/31/23
 4        RSPO Certified  RSPO Certified, IP                        3/31/23
 ..                  ...                 ...                            ...
 764  Not RSPO Certified                 NaN                        3/31/23
 765  Not RSPO Certified                 NaN                        3/31/23
 766  Not RSPO Certified                 NaN                        3/31/23
 767  Not RSPO Certified                 NaN                        3/31/23
 768  Not RSPO Certified                 NaN                        3/31/23

      Latitude  Longitude  ... treeloss_ha_2021 treeloss_km_2022  \
 0       -2.25     -48.59  ...           214.92             2.11
 1        1.73     103.54  ...           321.48             1.63
 2       -5.62     150.24  ...           820.62             7.76
 3        6.00     117.40  ...           265.32             4.37
 4       -5.31     151.01  ...           640.08            14.17
 ..        ...        ...  ...              ...              ...
 764      1.18     117.90  ...            30.69             0.41
 765      1.89     100.95  ...          2146.86            26.45
 766      3.88      98.34  ...           212.76             1.90
 767     -2.56     104.77  ...          1274.85             6.16
 768     -4.36     151.95  ...          7207.11           314.43

     treeloss_ha_2022 sum_of_treeloss_km treeloss_sum_proportion_of_forest  \
 0             210.60             104.56                              0.27
 1             162.72              94.74                              0.74
 2             775.80             119.11                              0.07
 3             436.59             238.78                              0.77
 4            1416.78             100.81                              0.09
 ..               ...                ...                               ...
 764            41.22             221.14                              0.62
 765          2645.19             663.81                              0.46
 766           190.26              31.70                              0.49
 767           616.14             326.44                              0.65
 768         31443.39            1044.47                              0.22

     remaining_forest_km remaining_proportion_of_forest  \
 0                284.88                           0.73
 1                 32.73                           0.26
 2               1666.81                           0.93
 3                 69.49                           0.23
 4               1040.02                           0.91
 ..                  ...                            ...
 764              133.70                           0.38
 765              785.63                           0.54
 766               33.48                           0.51
 767              173.38                           0.35
 768             3664.61                           0.78

      Current Deforestation Score  Past Deforestation Score  Future Risk Score
 0                              2                         2                  3
 1                              3                         4                  3
 2                              2                         1                  3
 3                              3                         4                  2
 4                              3                         1                  3
 ..                           ...                       ...                ...
 764                            1                         3                  2
 765                            3                         3                  3
 766                            4                         3                  4
 767                            3                         4                  3
 768                            5                         1                  5

 [769 rows x 73 columns],
 'FrieslandCampina':             UML ID      years               Group Name  \
 0     PO1000000017  2021,2020                AGROPALMA
 1     PO1000000019  2020,2021  KULIM (MALAYSIA) BERHAD
 2     PO1000000020  2021,2020                    NBPOL
 3     PO1000000021  2020,2021       ROYAL GOLDEN EAGLE
 4     PO1000000052  2021,2020          IOI CORPORATION
 ...            ...        ...                      ...
 1316  PO1000011556  2021,2020                  UNKNOWN
 1317  PO1000011910       2020                  UNKNOWN
 1318  PO1000011918       2020                  UNKNOWN
 1319  PO1000012622       2020                  UNKNOWN
 1320  PO1000012852       2020                  UNKNOWN

                      Parent Company                  Mill Name  \
 0                         AGROPALMA                        CPA
 1            EPA MANAGEMENT SDN BHD                    SEDENAK
 2              NEW BRITAIN PALM OIL                       MOSA
 3              INTI INDOSAWIT SUBUR                   BUATAN I
 4     PAMOL ESTATES (SABAH) SDN BHD                PAMOL SABAH
 ...                             ...                        ...
 1316           MERLUNG INTI LESTARI       MERLUNG INTI LESTARI
 1317              MAHATO INTI SAWIT          MAHATO INTI SAWIT
 1318                   ASTANA ENDAH               ASTANA ENDAH
 1319                  PALMARIS RAYA              PALMARIS RAYA
 1320      YUNI BERSAUDARA SEJAHTERA  YUNI BERSAUDARA SEJAHTERA

              RSPO Status           RSPO Type Date RSPO Certification Status  \
 0     Not RSPO Certified                 NaN                        3/31/23
 1         RSPO Certified  RSPO Certified, MB                        3/31/23
 2         RSPO Certified  RSPO Certified, IP                        3/31/23
 3         RSPO Certified  RSPO Certified, MB                        3/31/23
 4         RSPO Certified  RSPO Certified, IP                        3/31/23
 ...                  ...                 ...                            ...
 1316  Not RSPO Certified                 NaN                        3/31/23
 1317  Not RSPO Certified                 NaN                        3/31/23
 1318  Not RSPO Certified                 NaN                        3/31/23
 1319  Not RSPO Certified                 NaN                        3/31/23
 1320  Not RSPO Certified                 NaN                        3/31/23

       Latitude  Longitude  ... treeloss_ha_2021 treeloss_km_2022  \
 0        -2.25     -48.59  ...           214.92             2.11
 1         1.73     103.54  ...           321.48             1.63
 2        -5.62     150.24  ...           820.62             7.76
 3         0.43     101.82  ...           112.95             1.00
 4         6.00     117.40  ...           265.32             4.37
 ...        ...        ...  ...              ...              ...
 1316     -1.33     103.27  ...            98.91             1.03
 1317      1.37     100.30  ...            53.19             0.32
 1318      4.19     100.81  ...           288.90             2.14
 1319      0.44      99.26  ...           734.85             8.44
 1320     -0.03     101.19  ...          3695.49            40.01

      treeloss_ha_2022 sum_of_treeloss_km treeloss_sum_proportion_of_forest  \
 0              210.60             104.56                              0.27
 1              162.72              94.74                              0.74
 2              775.80             119.11                              0.07
 3               99.72              51.22                              0.64
 4              436.59             238.78                              0.77
 ...               ...                ...                               ...
 1316           102.69              48.02                              0.77
 1317            32.22               6.56                              0.52
 1318           213.57              33.69                              0.73
 1319           844.02             263.23                              0.76
 1320          4000.59             667.27                              0.27

      remaining_forest_km remaining_proportion_of_forest  \
 0                 284.88                           0.73
 1                  32.73                           0.26
 2                1666.81                           0.93
 3                  29.00                           0.36
 4                  69.49                           0.23
 ...                  ...                            ...
 1316               14.11                           0.23
 1317                6.05                           0.48
 1318               12.24                           0.27
 1319               83.54                           0.24
 1320             1782.05                           0.73

       Current Deforestation Score  Past Deforestation Score  Future Risk Score
 0                               2                         2                  3
 1                               3                         4                  3
 2                               2                         1                  3
 3                               3                         4                  3
 4                               3                         4                  2
 ...                           ...                       ...                ...
 1316                            3                         4                  3
 1317                            4                         3                  4
 1318                            5                         4                  4
 1319                            3                         4                  3
 1320                            3                         2                  3

 [1321 rows x 73 columns],
 'General Mills':             UML ID      years               Group Name  \
 0     PO1000000017  2021,2020                AGROPALMA
 1     PO1000000019  2021,2020  KULIM (MALAYSIA) BERHAD
 2     PO1000000020  2021,2020                    NBPOL
 3     PO1000000021  2021,2020       ROYAL GOLDEN EAGLE
 4     PO1000000052  2021,2020          IOI CORPORATION
 ...            ...        ...                      ...
 1737  PO1000012846       2021                  UNKNOWN
 1738  PO1000012848  2021,2020                  UNKNOWN
 1739  PO1000012849       2021                  UNKNOWN
 1740  PO1000012851       2021                  UNKNOWN
 1741  PO1000012852       2021                  UNKNOWN

                      Parent Company                  Mill Name  \
 0                         AGROPALMA                        CPA
 1            EPA MANAGEMENT SDN BHD                    SEDENAK
 2              NEW BRITAIN PALM OIL                       MOSA
 3              INTI INDOSAWIT SUBUR                   BUATAN I
 4     PAMOL ESTATES (SABAH) SDN BHD                PAMOL SABAH
 ...                             ...                        ...
 1737          PT CITRA AGRO KENCANA    CITRA AGRO KENCANA MILL
 1738                     ARSI GROUP     ARSI GRIYA PLANTATIONS
 1739            PALMA BUMI LESTARI         PALMA BUMI LESTARI
 1740            BUKIT JEJER SUKSES         BUKIT JEJER SUKSES
 1741      YUNI BERSAUDARA SEJAHTERA  YUNI BERSAUDARA SEJAHTERA

              RSPO Status           RSPO Type Date RSPO Certification Status  \
 0     Not RSPO Certified                 NaN                        3/31/23
 1         RSPO Certified  RSPO Certified, MB                        3/31/23
 2         RSPO Certified  RSPO Certified, IP                        3/31/23
 3         RSPO Certified  RSPO Certified, MB                        3/31/23
 4         RSPO Certified  RSPO Certified, IP                        3/31/23
 ...                  ...                 ...                            ...
 1737  Not RSPO Certified                 NaN                        3/31/23
 1738  Not RSPO Certified                 NaN                        3/31/23
 1739  Not RSPO Certified                 NaN                        3/31/23
 1740  Not RSPO Certified                 NaN                        3/31/23

In [32]:
# Visualize the colgate dataframe as an example
companies["Colgate"].head(25)

,UML ID,years,Group Name,Parent Company,Mill Name,RSPO Status,RSPO Type,Date RSPO Certification Status,Latitude,Longitude,...,treeloss_ha_2021,treeloss_km_2022,treeloss_ha_2022,sum_of_treeloss_km,treeloss_sum_proportion_of_forest,remaining_forest_km,remaining_proportion_of_forest,Current Deforestation Score,Past Deforestation Score,Future Risk Score
0,PO1000000019,"2021,2020,2019,2018,2017",KULIM (MALAYSIA) BERHAD,EPA MANAGEMENT SDN BHD,SEDENAK,RSPO Certified,"RSPO Certified, MB",3/31/23,1.73,103.54,...,321.48,1.63,162.72,94.74,0.74,32.73,0.26,3,4,3
1,PO1000000020,2018,NBPOL,NEW BRITAIN PALM OIL,MOSA,RSPO Certified,"RSPO Certified, IP",3/31/23,-5.62,150.24,...,820.62,7.76,775.80,119.11,0.07,1666.81,0.93,2,1,3
2,PO1000000021,"2018,2017,2020,2021,2019",ROYAL GOLDEN EAGLE,INTI INDOSAWIT SUBUR,BUATAN I,RSPO Certified,"RSPO Certified, MB",3/31/23,0.43,101.82,...,112.95,1.00,99.72,51.22,0.64,29.00,0.36,3,4,3
3,PO1000000052,"2021,2019,2018,2020",IOI CORPORATION,PAMOL ESTATES (SABAH) SDN BHD,PAMOL SABAH,RSPO Certified,"RSPO Certified, IP",3/31/23,6.00,117.40,...,265.32,4.37,436.59,238.78,0.77,69.49,0.23,3,4,2
4,PO1000000054,"2021,2019,2017,2018",MUSIM MAS,MUSIM MAS HOLDINGS PTE LTD,BATANG KULIM,RSPO Certified,"RSPO Certified, IP",3/31/23,0.08,102.03,...,511.47,9.88,987.75,226.85,0.84,42.36,0.16,4,5,3
5,PO1000000058,"2017,2018,2020,2019,2021",CARGILL,HINDOLI,SUNGAI LILIN,RSPO Certified,"RSPO Certified, IP",3/31/23,-2.61,104.13,...,161.01,2.63,263.07,49.68,0.72,19.19,0.28,4,4,3
6,PO1000000063,"2019,2020,2018,2017",SIME DARBY,SIME DARBY PLANTATION BHD,BINUANG (SOU 28),RSPO Certified,"RSPO Certified, IP",3/31/23,4.70,118.06,...,261.54,2.49,248.85,103.19,0.49,108.35,0.51,3,3,3
7,PO1000000064,"2018,2017,2019,2020",SIME DARBY,SIME DARBY PLANTATION BHD,MEROTAI (SOU 30),RSPO Certified,"RSPO Certified, MB",3/31/23,4.37,117.83,...,1237.95,12.48,1248.03,144.00,0.30,334.64,0.70,4,2,4
8,PO1000000065,"2020,2018,2019",SIME DARBY,SIME DARBY PLANTATION BHD,SANDAKAN BAY (SOU 26),RSPO Certified,"RSPO Certified, MB",3/31/23,5.64,118.17,...,931.23,7.61,760.68,137.38,0.43,180.24,0.57,4,3,4
9,PO1000000066,"2019,2017,2018",WILMAR GROUP,SABAHMAS PLANTATION SDN BHD,SABAHMAS,RSPO Certified,"RSPO Certified, MB",3/31/23,5.18,118.41,...,953.46,2.10,210.33,89.29,1.00,0.00,0.00,5,5,3
10,PO1000000091,"2017,2018,2020,2021,2019",WILMAR GROUP,SAREMAS SDN BHD,SAREMAS 1,RSPO Certified,"RSPO Certified, MB",3/31/23,3.52,113.74,...,44.10,0.69,68.76,117.32,1.00,0.38,0.00,2,5,1
11,PO1000000092,2019,MUSIM MAS,AGRO WIRATAMA,AGROWIRATAMA,RSPO Certified,"RSPO Certified, IP",3/31/23,0.20,99.63,...,1883.88,7.98,798.03,231.50,0.77,70.72,0.23,5,4,3
12,PO1000000093,"2019,2021,2017,2018,2020",WILMAR GROUP,SAREMAS SDN BHD,SAREMAS 2,RSPO Certified,"RSPO Certified, IP",3/31/23,3.45,113.77,...,1879.11,6.09,609.21,142.53,0.89,17.04,0.11,5,5,4
13,PO1000000094,"2021,2020,2019,2018,2017",IOI CORPORATION,IOI CORPORATION BHD,GOMALI,RSPO Certified,"RSPO Certified, IP",3/31/23,2.61,102.68,...,304.47,3.75,374.76,138.82,0.91,12.92,0.09,3,5,2
14,PO1000000095,"2018,2017,2021,2020,2019",SIPEF,EASTERN SUMATERA INDONESIA,BUKIT MARADJA,RSPO Certified,"RSPO Certified, IP",3/31/23,3.01,99.24,...,76.95,0.99,98.55,29.64,0.83,6.23,0.17,4,5,3
15,PO1000000097,"2019,2018,2020,2021",SIME DARBY,SIME DARBY PLANTATION BHD,EAST (SOU 8),RSPO Certified,"RSPO Certified, IP",3/31/23,2.88,101.44,...,232.29,1.11,111.24,39.13,0.53,35.34,0.47,3,3,3
16,PO1000000098,"2020,2021,2019,2018",SIME DARBY,SIME DARBY PLANTATION BHD,TANAH MERAH (SOU 14),RSPO Certified,"RSPO Certified, IP",3/31/23,2.66,101.79,...,293.13,3.12,312.48,94.51,0.88,13.30,0.12,4,5,3
17,PO1000000099,"2017,2018,2020,2021,2019",SIPEF,TOLAN TIGA INDONESIA,PERLABIAN,RSPO Certified,"RSPO Certified, IP",3/31/23,2.06,100.08,...,103.50,3.04,303.75,72.95,0.65,38.60,0.35,3,4,3
18,PO1000000103,"2019,2017,2018,2020,2021",SIME DARBY,SIME DARBY PLANTATION BHD,WEST (SOU 9),RSPO Certified,"RSPO Certified, IP",3/31/23,2.90,101.36,...,352.98,3.05,304.74,91.24,0.46,105.26,0.54,3,3,3
19,PO1000000104,"2020,2021,2019,2018,2017",SIME DARBY,SIME DARBY PLANTATION BHD,SUNGAI DINGIN (SOU 1),RSPO Certified,"RSPO Certified, MB",3/31/23,5.39,100.71,...,541.89,5.81,580.86,103.95,0.30,243.83,0.70,3,2,3
20,PO1000000106,2019,MUSIM MAS,SUKAJADI SAWIT MEKAR,SUKAJADI SAWIT MEKAR 1,RSPO Certified,"RSPO Certified, IP",3/31/23,-2.38,112.54,...,171.81,1.83,182.61,160.69,1.00,0.38,0.00,3,5,1
21,PO1000000107,"2019,2020,2021,2017,2018",SIME DARBY,SIME INDO AGRO,BUKIT AJONG,RSPO Certified,"RSPO Certified, MB",3/31/23,0.27,110.48,...,2362.68,9.24,923.85,294.65,0.70,129.06,0.30,5,4,3
22,PO1000000109,"2017,2018,2019,2020,2021",IOI CORPORATION,IOI CORPORATION BHD,PAMOL KLUANG,RSPO Certified,"RSPO Certified, IP",3/31/23,2.11,103.39,...,424.89,1.79,179.01,117.25,0.81,27.48,0.19,3,5,3
23,PO1000000110,"2020,2018,2017,2021,2019",IOI CORPORATION,IOI CORPORATION BHD,SAKILAN,RSPO Certified,"RSPO Certified, IP",3/31/23,5.84,117.84,...,181.89,2.13,213.48,48.16,0.55,39.20,0.45,3,3,3
24,PO1000000118,"2019,2021,2020,2017,2018",IOI CORPORATION,IOI CORPORATION BHD,BATURONG,RSPO Certified,"RSPO Certified, IP",3/31/23,4.76,118.09,...,121.68,3.89,389.25,63.29,0.98,1.36,0.02,5,5,3

In [33]:
companies["Colgate"].columns

Index(['UML ID', 'years', 'Group Name', 'Parent Company', 'Mill Name',
       'RSPO Status', 'RSPO Type', 'Date RSPO Certification Status',
       'Latitude', 'Longitude', 'GPS coordinates', 'ISO', 'Country',
       'Province', 'District', 'Confidence level', 'Alternative name',
       'km_forest_area_00', 'ha_forest_area_00', 'km_area', 'km_0', 'ha_0',
       'treeloss_km_2001', 'treeloss_ha_2001', 'treeloss_km_2002',
       'treeloss_ha_2002', 'treeloss_km_2003', 'treeloss_ha_2003',
       'treeloss_km_2004', 'treeloss_ha_2004', 'treeloss_km_2005',
       'treeloss_ha_2005', 'treeloss_km_2006', 'treeloss_ha_2006',
       'treeloss_km_2007', 'treeloss_ha_2007', 'treeloss_km_2008',
       'treeloss_ha_2008', 'treeloss_km_2009', 'treeloss_ha_2009',
       'treeloss_km_2010', 'treeloss_ha_2010', 'treeloss_km_2011',
       'treeloss_ha_2011', 'treeloss_km_2012', 'treeloss_ha_2012',
       'treeloss_km_2013', 'treeloss_ha_2013', 'treeloss_km_2014',
       'treeloss_ha_2014', 'treeloss_km_2015', 'treeloss_ha_2015',
       'treeloss_km_2016', 'treeloss_ha_2016', 'treeloss_km_2017',
       'treeloss_ha_2017', 'treeloss_km_2018', 'treeloss_ha_2018',
       'treeloss_km_2019', 'treeloss_ha_2019', 'treeloss_km_2020',
       'treeloss_ha_2020', 'treeloss_km_2021', 'treeloss_ha_2021',
       'treeloss_km_2022', 'treeloss_ha_2022', 'sum_of_treeloss_km',
       'treeloss_sum_proportion_of_forest', 'remaining_forest_km',
       'remaining_proportion_of_forest', 'Current Deforestation Score',
       'Past Deforestation Score', 'Future Risk Score'],
      dtype='object')

In [34]:
# Clean the dataframes and only save the rows with Sumatra provinces
def prepare_df(df):

  """
  Create a dataframe with only information of Sumatra, Indonesia
  """

  # Save data from Sumatra in specific (cut the rest of the columns and rows)
  df = df[df["Province"].isin(provinces)]

  # Save the columns we consider important
  df = df.loc[:, "UML ID":"sum_of_treeloss_km"].reset_index()
  df.drop(columns = df.loc[:, "Confidence level" : "treeloss_ha_2022"], inplace = True)

  # Sort data by province and parent company columns
  df_prov = df.loc[:, ["Province", "Parent Company", "RSPO Status", "sum_of_treeloss_km"]].sort_values(by = ["Province", "Parent Company"])
  df_prov = df_prov.groupby(["Province", "Parent Company", "RSPO Status"])["sum_of_treeloss_km"].sum()

  return df_prov.reset_index()

In [35]:
# Prepare the dataframe for each company
for company in companies:

    company_df = companies[company] # Dataframe
    companies[company] = prepare_df(company_df) # Edit dataframe

companies

{'Colgate':            Province                       Parent Company         RSPO Status  \
 0              Aceh                 ANUGRAH FAJAR REZEKI  Not RSPO Certified
 1              Aceh              BANGUN SEMPURNA LESTARI  Not RSPO Certified
 2              Aceh                BEURATA SUBUR PERSADA  Not RSPO Certified
 3              Aceh                        BLANG KETUMBA  Not RSPO Certified
 4              Aceh                    BOSWA MEGALOPOLIS  Not RSPO Certified
 ..              ...                                  ...                 ...
 551  Sumatera Utara                     UMBUL MAS WISESA      RSPO Certified
 552  Sumatera Utara  UNITED KINGDOM INDONESIA PLANTATION  Not RSPO Certified
 553  Sumatera Utara                VAREM SAWIT CEMERLANG  Not RSPO Certified
 554  Sumatera Utara              VICTORINDO ALAM LESTARI  Not RSPO Certified
 555  Sumatera Utara                YAPUTRA ALFA PALMINDO  Not RSPO Certified

      sum_of_treeloss_km
 0                 85.64
 1                397.91
 2                278.23
 3                494.62
 4                527.55
 ..                  ...
 551              197.00
 552               26.22
 553               92.82
 554              321.54
 555               14.09

 [556 rows x 4 columns],
 'Ferrero':            Province                       Parent Company         RSPO Status  \
 0              Aceh                 ANUGRAH FAJAR REZEKI  Not RSPO Certified
 1              Aceh              BANGUN SEMPURNA LESTARI  Not RSPO Certified
 2              Aceh                BEURATA SUBUR PERSADA  Not RSPO Certified
 3              Aceh                        BLANG KETUMBA  Not RSPO Certified
 4              Aceh                  BUMI DAYA AGROTAMAS  Not RSPO Certified
 ..              ...                                  ...                 ...
 307  Sumatera Utara                  TUNAS HARAPAN SAWIT  Not RSPO Certified
 308  Sumatera Utara                     UMBUL MAS WISESA      RSPO Certified
 309  Sumatera Utara  UNITED KINGDOM INDONESIA PLANTATION  Not RSPO Certified
 310  Sumatera Utara                VAREM SAWIT CEMERLANG  Not RSPO Certified
 311  Sumatera Utara                YAPUTRA ALFA PALMINDO  Not RSPO Certified

      sum_of_treeloss_km
 0                 85.64
 1                397.91
 2                278.23
 3                494.62
 4                140.24
 ..                  ...
 307                6.42
 308              197.00
 309               26.22
 310               92.82
 311               14.09

 [312 rows x 4 columns],
 'FrieslandCampina':            Province                       Parent Company         RSPO Status  \
 0              Aceh                        BLANG KETUMBA  Not RSPO Certified
 1              Aceh                        DELIMA MAKMUR  Not RSPO Certified
 2              Aceh                        ENSEM LESTARI  Not RSPO Certified
 3              Aceh                         ENSEM SAWITA  Not RSPO Certified
 4              Aceh             FAJAR BAIZURI & BROTHERS  Not RSPO Certified
 ..              ...                                  ...                 ...
 439  Sumatera Utara                  TUNAS HARAPAN SAWIT  Not RSPO Certified
 440  Sumatera Utara                                UMADA  Not RSPO Certified
 441  Sumatera Utara                     UMBUL MAS WISESA      RSPO Certified
 442  Sumatera Utara  UNITED KINGDOM INDONESIA PLANTATION  Not RSPO Certified
 443  Sumatera Utara                VAREM SAWIT CEMERLANG  Not RSPO Certified

      sum_of_treeloss_km
 0                494.62
 1                 31.71
 2                 90.37
 3                 79.56
 4                 28.96
 ..                  ...
 439                6.42
 440               50.53
 441              197.00
 442               26.22
 443               92.82

 [444 rows x 4 columns],
 'General Mills':            Province                       Parent Company         RSPO Status  \
 0              Aceh                 ANUGRAH FAJAR REZEKI  Not RSPO Certified
 1              Aceh              BANGUN SEMPURNA LESTARI  Not RSPO Certified
 2              Aceh                BEURATA SUBUR PERSADA  Not RSPO Certified
 3              Aceh                        BLANG KETUMBA  Not RSPO Certified
 4              Aceh                  BUMI DAYA AGROTAMAS  Not RSPO Certified
 ..              ...                                  ...                 ...
 550  Sumatera Utara                     UMBUL MAS WISESA      RSPO Certified
 551  Sumatera Utara  UNITED KINGDOM INDONESIA PLANTATION  Not RSPO Certified
 552  Sumatera Utara                VAREM SAWIT CEMERLANG  Not RSPO Certified
 553  Sumatera Utara              VICTORINDO ALAM LESTARI  Not RSPO Certified
 554  Sumatera Utara                YAPUTRA ALFA PALMINDO  Not RSPO Certified

      sum_of_treeloss_km
 0                 85.64
 1                397.91
 2                278.23
 3                494.62
 4                140.24
 ..                  ...
 550              197.00
 551               26.22
 552               92.82
 553              321.54
 554               14.09

 [555 rows x 4 columns],
 'Hershey':            Province                       Parent Company         RSPO Status  \
 0              Aceh                 ANUGRAH FAJAR REZEKI  Not RSPO Certified
 1              Aceh              BANGUN SEMPURNA LESTARI  Not RSPO Certified
 2              Aceh                BEURATA SUBUR PERSADA  Not RSPO Certified
 3              Aceh                        BLANG KETUMBA  Not RSPO Certified
 4              Aceh                  BUMI DAYA AGROTAMAS  Not RSPO Certified
 ..              ...                                  ...                 ...
 500  Sumatera Utara                     UMBUL MAS WISESA      RSPO Certified
 501  Sumatera Utara  UNITED KINGDOM INDONESIA PLANTATION  Not RSPO Certified
 502  Sumatera Utara                VAREM SAWIT CEMERLANG  Not RSPO Certified
 503  Sumatera Utara              VICTORINDO ALAM LESTARI  Not RSPO Certified
 504  Sumatera Utara                YAPUTRA ALFA PALMINDO  Not RSPO Certified

      sum_of_treeloss_km
 0                 85.64
 1                397.91
 2                278.23
 3                494.62
 4                140.24
 ..                  ...
 500              197.00
 501               26.22
 502               92.82
 503              321.54
 504               14.09

 [505 rows x 4 columns],
 'Johnson & Johnson':            Province                       Parent Company         RSPO Status  \
 0              Aceh                      AGRA BUMI NIAGA  Not RSPO Certified
 1              Aceh                 ANUGRAH FAJAR REZEKI  Not RSPO Certified
 2              Aceh              BANGUN SEMPURNA LESTARI  Not RSPO Certified
 3              Aceh                BEURATA SUBUR PERSADA  Not RSPO Certified
 4              Aceh                        BLANG KETUMBA  Not RSPO Certified
 ..              ...                                  ...                 ...
 563  Sumatera Utara                     UMBUL MAS WISESA      RSPO Certified
 564  Sumatera Utara  UNITED KINGDOM INDONESIA PLANTATION  Not RSPO Certified
 565  Sumatera Utara                VAREM SAWIT CEMERLANG  Not RSPO Certified
 566  Sumatera Utara              VICTORINDO ALAM LESTARI  Not RSPO Certified
 567  Sumatera Utara                YAPUTRA ALFA PALMINDO  Not RSPO Certified

      sum_of_treeloss_km
 0                335.31
 1                 85.64
 2                397.91
 3                278.23
 4                494.62
 ..                  ...
 563              197.00
 564               26.22
 565               92.82
 566              321.54
 567               14.09

 [568 rows x 4 columns],
 'Kellogg':            Province                       Parent Company         RSPO Status  \
 0              Aceh                 ANUGRAH FAJAR REZEKI  Not RSPO Certified
 1              Aceh              BANGUN SEMPURNA LESTARI  Not RSPO Certified
 2              Aceh                BEURATA SUBUR PERSADA  Not RSPO Certified
 3              Aceh                        BLANG KETUMBA  Not RSPO Certified
 4              Aceh                    BOSWA MEGALOPOLIS  Not RSPO Certified
 ..              ...                                  ...                 ...
 503  Sumatera Utara                                UMADA  Not RSPO Certified
 504  Sumatera Utara                     UMBUL MAS WISESA      RSPO Certified
 505  Sumatera Utara  UNITED KINGDOM INDONESIA PLANTATION  Not RSPO Certified
 506  Sumatera Utara                VAREM SAWIT CEMERLANG  Not RSPO Certified
 507  Sumatera Utara                YAPUTRA ALFA PALMINDO  Not RSPO Certified

      sum_of_treeloss_km
 0                 85.64
 1                397.91
 2                278.23
 3                494.62
 4                527.55
 ..                  ...
 503               50.53
 504              197.00
 505               26.22
 506               92.82
 507               14.09

 [508 rows x 4 columns],
 'L_OREAL':            Province                       Parent Company         RSPO Status  \
 0              Aceh                      AGRA BUMI NIAGA  Not RSPO Certified
 1              Aceh                 ANUGRAH FAJAR REZEKI  Not RSPO Certified
 2              Aceh              BANGUN SEMPURNA LESTARI  Not RSPO Certified
 3              Aceh                BEURATA SUBUR PERSADA  Not RSPO Certified
 4              Aceh                        BLANG KETUMBA  Not RSPO Certified
 ..              ...                                  ...                 ...
 512  Sumatera Utara                  TUNAS HARAPAN SAWIT  Not RSPO Certified
 513  Sumatera Utara                     UMBUL MAS WISESA      RSPO Certified
 514  Sumatera Utara  UNITED KINGDOM INDONESIA PLANTATION  Not RSPO Certified
 515  Sumatera Utara                VAREM SAWIT CEMERLANG  Not RSPO Certified
 516  Sumatera Utara                YAPUTRA ALFA PALMINDO  Not RSPO Certified

      sum_of_treeloss_km
 0                335.31
 1                 85.64
 2                397.91
 3                278.23
 4                494.62
 ..                  ...
 512                6.42
 513              197.00
 514               26.22
 515               92.82
 516               14.09

 [517 rows x 4 columns],
 'Mars':            Province           Parent Company         RSPO Status  \
 0              Aceh     ANUGRAH FAJAR REZEKI  Not RSPO Certified
 1              Aceh  BANGUN SEMPURNA LESTARI  Not RSPO Certified
 2              Aceh    BEURATA SUBUR PERSADA  Not RSPO Certified
 3              Aceh            BLANG KETUMBA  Not RSPO Certified
 4              Aceh      BUMI DAYA AGROTAMAS  Not RSPO Certified
 ..              ...                      ...                 ...
 150  Sumatera Utara        SUMBER TANI AGUNG  Not RSPO Certified
 151  Sumatera Utara      TUNAS HARAPAN SAWIT  Not RSPO Certified
 152  Sumatera Utara                    UMADA  Not RSPO Certified
 153  Sumatera Utara    VAREM SAWIT CEMERLANG  Not RSPO Certified
 154  Sumatera Utara    YAPUTRA ALFA PALMINDO  Not RSPO Certified

      sum_of_treeloss_km
 0                 85.64
 1                397.91
 2                278.23
 3                494.62
 4                140.24
 ..                  ...
 150               97.56
 151                6.42
 152               50.53
 153               92.82
 154               14.09

 [155 rows x 4 columns],
 'Mondelez':            Province                       Parent Company         RSPO Status  \
 0              Aceh                      AGRA BUMI NIAGA  Not RSPO Certified
 1              Aceh                 ANUGRAH FAJAR REZEKI  Not RSPO Certified
 2              Aceh              BANGUN SEMPURNA LESTARI  Not RSPO Certified
 3              Aceh                BEURATA SUBUR PERSADA  Not RSPO Certified
 4              Aceh                        BLANG KETUMBA  Not RSPO Certified
 ..              ...                                  ...                 ...
 567  Sumatera Utara                     UMBUL MAS WISESA      RSPO Certified
 568  Sumatera Utara  UNITED KINGDOM INDONESIA PLANTATION  Not RSPO Certified
 569  Sumatera Utara                VAREM SAWIT CEMERLANG  Not RSPO Certified
 570  Sumatera Utara              VICTORINDO ALAM LESTARI  Not RSPO Certified
 571  Sumatera Utara                YAPUTRA ALFA PALMINDO  Not RSPO Certified

      sum_of_treeloss_km
 0                335.31
 1                 85.64
 2                397.91
 3                278.23
 4                494.62
 ..                  ...
 567              197.00
 568               26.22
 569               92.82
 570              321.54
 571               14.09

 [572 rows x 4 columns],
 'Nestle':            Province                       Parent Company         RSPO Status  \
 0              Aceh                 ANUGRAH FAJAR REZEKI  Not RSPO Certified
 1              Aceh              BANGUN SEMPURNA LESTARI  Not RSPO Certified
 2              Aceh                BEURATA SUBUR PERSADA  Not RSPO Certified
 3              Aceh                        BLANG KETUMBA  Not RSPO Certified
 4              Aceh                  BUMI DAYA AGROTAMAS  Not RSPO Certified
 ..              ...                                  ...                 ...
 519  Sumatera Utara                     UMBUL MAS WISESA      RSPO Certified
 520  Sumatera Utara  UNITED KINGDOM INDONESIA PLANTATION  Not RSPO Certified
 521  Sumatera Utara                VAREM SAWIT CEMERLANG  Not RSPO Certified
 522  Sumatera Utara              VICTORINDO ALAM LESTARI  Not RSPO Certified
 523  Sumatera Utara                YAPUTRA ALFA PALMINDO  Not RSPO Certified

      sum_of_treeloss_km
 0                 85.64
 1                397.91
 2                278.23
 3                494.62
 4                140.24
 ..                  ...
 519              197.00
 520               26.22
 521               92.82
 522              321.54
 523               14.09

 [524 rows x 4 columns],
 'PepsiCo':            Province                       Parent Company         RSPO Status  \
 0              Aceh                 ANUGRAH FAJAR REZEKI  Not RSPO Certified
 1              Aceh              BANGUN SEMPURNA LESTARI  Not RSPO Certified
 2              Aceh                BEURATA SUBUR PERSADA  Not RSPO Certified
 3              Aceh                        BLANG KETUMBA  Not RSPO Certified
 4              Aceh                    BOSWA MEGALOPOLIS  Not RSPO Certified
 ..              ...                                  ...                 ...
 563  Sumatera Utara                                UMADA  Not RSPO Certified
 564  Sumatera Utara                     UMBUL MAS WISESA      RSPO Certified
 565  Sumatera Utara  UNITED KINGDOM INDONESIA PLANTATION  Not RSPO Certified
 566  Sumatera Utara                VAREM SAWIT CEMERLANG  Not RSPO Certified
 567  Sumatera Utara                YAPUTRA ALFA PALMINDO  Not RSPO Certified

      sum_of_treeloss_km
 0                 85.64
 1                397.91
 2                278.23
 3                494.62
 4                527.55
 ..                  ...
 563               50.53
 564              197.00
 565               26.22
 566               92.82
 567               14.09

 [568 rows x 4 columns],
 'Procter & Gamble':            Province                       Parent Company         RSPO Status  \
 0              Aceh                 ANUGRAH FAJAR REZEKI  Not RSPO Certified
 1              Aceh              BANGUN SEMPURNA LESTARI  Not RSPO Certified
 2              Aceh                BEURATA SUBUR PERSADA  Not RSPO Certified
 3              Aceh                        BLANG KETUMBA  Not RSPO Certified
 4              Aceh                  BUMI DAYA AGROTAMAS  Not RSPO Certified
 ..              ...                                  ...                 ...
 551  Sumatera Utara                     UMBUL MAS WISESA      RSPO Certified
 552  Sumatera Utara  UNITED KINGDOM INDONESIA PLANTATION  Not RSPO Certified
 553  Sumatera Utara                VAREM SAWIT CEMERLANG  Not RSPO Certified
 554  Sumatera Utara              VICTORINDO ALAM LESTARI  Not RSPO Certified
 555  Sumatera Utara                YAPUTRA ALFA PALMINDO  Not RSPO Certified

      sum_of_treeloss_km
 0                 85.64
 1                397.91
 2                278.23
 3                494.62
 4                140.24
 ..                  ...
 551              197.00
 552               26.22
 553               92.82
 554              321.54
 555               14.09

 [556 rows x 4 columns],
 'Reckitt Benckiser (RB)':            Province                       Parent Company         RSPO Status  \
 0              Aceh                      AGRA BUMI NIAGA  Not RSPO Certified
 1              Aceh                 ANUGRAH FAJAR REZEKI  Not RSPO Certified
 2              Aceh              BANGUN SEMPURNA LESTARI  Not RSPO Certified
 3              Aceh                BEURATA SUBUR PERSADA  Not RSPO Certified
 4              Aceh                        BLANG KETUMBA  Not RSPO Certified
 ..              ...                                  ...                 ...
 553  Sumatera Utara                     UMBUL MAS WISESA      RSPO Certified
 554  Sumatera Utara  UNITED KINGDOM INDONESIA PLANTATION  Not RSPO Certified
 555  Sumatera Utara                VAREM SAWIT CEMERLANG  Not RSPO Certified
 556  Sumatera Utara              VICTORINDO ALAM LESTARI  Not RSPO Certified
 557  Sumatera Utara                YAPUTRA ALFA PALMINDO  Not RSPO Certified

      sum_of_treeloss_km
 0                335.31
 1                 85.64
 2                397.91
 3                278.23
 4                494.62
 ..                  ...
 553              197.00
 554               26.22
 555               92.82
 556              321.54
 557               14.09

 [558 rows x 4 columns],
 'Unilever':            Province                       Parent Company         RSPO Status  \
 0              Aceh                 ANUGRAH FAJAR REZEKI  Not RSPO Certified
 1              Aceh              BANGUN SEMPURNA LESTARI  Not RSPO Certified
 2              Aceh                BEURATA SUBUR PERSADA  Not RSPO Certified
 3              Aceh                     BIMA DESA SAWITA  Not RSPO Certified
 4              Aceh                        BLANG KETUMBA  Not RSPO Certified
 ..              ...                                  ...                 ...
 529  Sumatera Utara                     UMBUL MAS WISESA      RSPO Certified
 530  Sumatera Utara  UNITED KINGDOM INDONESIA PLANTATION  Not RSPO Certified
 531  Sumatera Utara                VAREM SAWIT CEMERLANG  Not RSPO Certified
 532  Sumatera Utara              VICTORINDO ALAM LESTARI  Not RSPO Certified
 533  Sumatera Utara                YAPUTRA ALFA PALMINDO  Not RSPO Certified

      sum_of_treeloss_km
 0                 85.64
 1                397.91
 2                278.23
 3                 80.67
 4                494.62
 ..                  ...
 529              197.00
 530               26.22
 531               92.82
 532              321.54
 533               14.09

 [534 rows x 4 columns]}

In [36]:
companies["Colgate"].columns

Index(['Province', 'Parent Company', 'RSPO Status', 'sum_of_treeloss_km'], dtype='object')

In [37]:
# Visualize the Colgate dataframe
companies["Colgate"]

,Province,Parent Company,RSPO Status,sum_of_treeloss_km
0,Aceh,ANUGRAH FAJAR REZEKI,Not RSPO Certified,85.64
1,Aceh,BANGUN SEMPURNA LESTARI,Not RSPO Certified,397.91
2,Aceh,BEURATA SUBUR PERSADA,Not RSPO Certified,278.23
3,Aceh,BLANG KETUMBA,Not RSPO Certified,494.62
4,Aceh,BOSWA MEGALOPOLIS,Not RSPO Certified,527.55
...,...,...,...,...
551,Sumatera Utara,UMBUL MAS WISESA,RSPO Certified,197.00
552,Sumatera Utara,UNITED KINGDOM INDONESIA PLANTATION,Not RSPO Certified,26.22
553,Sumatera Utara,VAREM SAWIT CEMERLANG,Not RSPO Certified,92.82
554,Sumatera Utara,VICTORINDO ALAM LESTARI,Not RSPO Certified,321.54
555,Sumatera Utara,YAPUTRA ALFA PALMINDO,Not RSPO Certified,14.09

In [90]:
# Dictionary with mill information
mill_info = pd.DataFrame()

# Iterate through the company dataframes and provinces
for company in companies:
  for p in provinces:
    
    # Temporary df with information of a specific province
    specific_company = companies[company]
    temp = specific_company[specific_company["Province"] == p]
    mill_count = temp["Parent Company"].nunique()

    # Group by the province and companies and add the sum of treeloss
    temp = temp.groupby(["Province"])["sum_of_treeloss_km"].sum().reset_index()
    temp["Mill Count"] = mill_count
    temp["Company"] = company
    
    # Save values in a dataframe
    mill_info = pd.concat([mill_info, temp])

# Reorganize the columns in the dataframe
mill_info = mill_info[["Company", "Province", "Mill Count", "sum_of_treeloss_km"]].reset_index().drop(columns = ["index"])
mill_info.head(24)

             Company          Province  Mill Count  sum_of_treeloss_km
0            Colgate              Aceh          34             5990.11
1            Colgate              Riau         177            44379.99
2            Colgate          Bengkulu          25             4378.83
3            Colgate  Sumatera Selatan          61            26717.66
4            Colgate    Sumatera Barat          30             5905.20
5            Colgate    Sumatera Utara         134            16137.76
6            Colgate             Jambi          64            18600.66
7            Colgate           Lampung          14             3641.41
8            Ferrero              Aceh          24             4680.95
9            Ferrero              Riau         103            24709.28
10           Ferrero          Bengkulu           7             1335.16
11           Ferrero  Sumatera Selatan          35            16849.12
12           Ferrero    Sumatera Barat           7             1633.45
13           Ferrero    Sumatera Utara          86            11668.76
14           Ferrero             Jambi          39            12713.69
15           Ferrero           Lampung           5              938.39
16  FrieslandCampina              Aceh          15             2083.78
17  FrieslandCampina              Riau         161            36813.71
18  FrieslandCampina          Bengkulu          17             2943.06
19  FrieslandCampina  Sumatera Selatan          56            22509.95
20  FrieslandCampina    Sumatera Barat          17             2843.62
21  FrieslandCampina    Sumatera Utara         101            10609.65
22  FrieslandCampina             Jambi          55            15775.05
23  FrieslandCampina           Lampung          11             2106.73

In [88]:
# Sort dataframe by mill counts and treeloss
mill_info.sort_values(by = ["Mill Count", "sum_of_treeloss_km"], ascending = False)

              Company        Province  Mill Count  sum_of_treeloss_km
41  Johnson & Johnson            Riau         180            44477.99
89            PepsiCo            Riau         179            43822.01
97   Procter & Gamble            Riau         178            43613.12
73           Mondelez            Riau         177            44683.05
1             Colgate            Riau         177            44379.99
..                ...             ...         ...                 ...
12            Ferrero  Sumatera Barat           7             1633.45
10            Ferrero        Bengkulu           7             1335.16
66               Mars        Bengkulu           7             1062.71
15            Ferrero         Lampung           5              938.39
71               Mars         Lampung           2              416.49

[120 rows x 4 columns]