In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import os

from google.colab import drive
drive.mount('/content/gdrive')

Mounted at /content/gdrive

In [2]:
# Provinces in Indonesia list
provinces = ["Aceh", "Riau", "Bengkulu", "Sumatera Selatan", "Sumatera Barat", "Sumatera Utara", "Jambi", "Lampung"]

In [3]:
# Dataframes for the 15 Palm Oil companies

# Company used as the example
colgate_mill_owners = pd.read_csv("/content/gdrive/MyDrive/PalmWatch/Colab Notebooks/Companies_Indonesia/PalmWatch_mill_csv/Colgate-Palmolive-Mill-Owners-2026-7-27.csv")
colgate_mill = pd.read_csv("/content/gdrive/MyDrive/PalmWatch/Colab Notebooks/Companies_Indonesia/PalmWatch_mill_csv/Colgate-Palmolive-Mills-2026-7-27.csv")

ferrero_mill = pd.read_csv("/content/gdrive/MyDrive/PalmWatch/Colab Notebooks/Companies_Indonesia/PalmWatch_mill_csv/Ferrero-Mills-2026-7-27.csv")
johnson_mill = pd.read_csv("/content/gdrive/MyDrive/PalmWatch/Colab Notebooks/Companies_Indonesia/PalmWatch_mill_csv/Johnson & Johnson-Mills-2026-7-27.csv")
loreal_mill = pd.read_csv("/content/gdrive/MyDrive/PalmWatch/Colab Notebooks/Companies_Indonesia/PalmWatch_mill_csv/L'OREAL-Mills-2026-7-27.csv")
unilever_mill = pd.read_csv("/content/gdrive/MyDrive/PalmWatch/Colab Notebooks/Companies_Indonesia/PalmWatch_mill_csv/Unilever-Mills-2026-7-28.csv")
rb_mill = pd.read_csv("/content/gdrive/MyDrive/PalmWatch/Colab Notebooks/Companies_Indonesia/PalmWatch_mill_csv/Reckitt Benckiser (RB)-Mills-2026-7-28.csv")
procter_gamble_mill = pd.read_csv("/content/gdrive/MyDrive/PalmWatch/Colab Notebooks/Companies_Indonesia/PalmWatch_mill_csv/Procter & Gamble-Mills-2026-7-28.csv")
pepsico_mill = pd.read_csv("/content/gdrive/MyDrive/PalmWatch/Colab Notebooks/Companies_Indonesia/PalmWatch_mill_csv/PepsiCo-Mills-2026-7-28.csv")
nestle_mill = pd.read_csv("/content/gdrive/MyDrive/PalmWatch/Colab Notebooks/Companies_Indonesia/PalmWatch_mill_csv/Nestle-Mills-2026-7-28.csv")
mondelez_mill = pd.read_csv("/content/gdrive/MyDrive/PalmWatch/Colab Notebooks/Companies_Indonesia/PalmWatch_mill_csv/Mondelez-Mills-2026-7-28.csv")
mars_mill = pd.read_csv("/content/gdrive/MyDrive/PalmWatch/Colab Notebooks/Companies_Indonesia/PalmWatch_mill_csv/Mars-Mills-2026-7-28.csv")
kellogg_mill = pd.read_csv("/content/gdrive/MyDrive/PalmWatch/Colab Notebooks/Companies_Indonesia/PalmWatch_mill_csv/Kellogg-Mills-2026-7-28.csv")
fries_camp_mill = pd.read_csv("/content/gdrive/MyDrive/PalmWatch/Colab Notebooks/Companies_Indonesia/PalmWatch_mill_csv/FrieslandCampina-Mills-2026-7-28.csv")
general_mill = pd.read_csv("/content/gdrive/MyDrive/PalmWatch/Colab Notebooks/Companies_Indonesia/PalmWatch_mill_csv/General Mills-Mills-2026-7-28.csv")
hershey_mill = pd.read_csv("/content/gdrive/MyDrive/PalmWatch/Colab Notebooks/Companies_Indonesia/PalmWatch_mill_csv/Hershey-Mills-2026-7-28.csv")

# DIctionary with company dataframes
companies = [{colgate_mill, ferrero_mill, johnson_mill, loreal_mill, unilever_mill, rb_mill, procter_gamble_mill, pepsico_mill, nestle_mill, mondelez_mill, mars_mill, kellogg_mill, fries_camp_mill, general_mill, hershey_mill}]
len(companies)

15

In [4]:
# Visualize the colgate dataframe as an example
colgate_mill_owners.head(25)

                                    Parent Company           Country  count
0                      FGV PALM INDUSTRIES SDN BHD          Malaysia     72
1                        SIME DARBY PLANTATION BHD          Malaysia     34
2                          PERKEBUNAN NUSANTARA IV         Indonesia     16
3                         PERKEBUNAN NUSANTARA III         Indonesia     12
4                           PERKEBUNAN NUSANTARA V         Indonesia     12
5                              IOI CORPORATION BHD          Malaysia     10
6   PERUSAHAAN PERKEBUNAN LONDON SUMATRA INDONESIA         Indonesia     10
7                             INTI INDOSAWIT SUBUR         Indonesia      9
8                          KUALA LUMPUR KEPONG BHD          Malaysia      9
9                                 SOCFIN INDONESIA         Indonesia      9
10                        PERKEBUNAN NUSANTARA VII         Indonesia      8
11                          SAWIT KINABALU SDN BHD          Malaysia      7
12                             GENTING SDC SDN BHD          Malaysia      7
13                       PERKEBUNAN NUSANTARA XIII         Indonesia      7
14                         PERKEBUNAN NUSANTARA VI         Indonesia      7
15                       KL-KEPONG (SABAH) SDN BHD          Malaysia      6
16                            KRESNA DUTA AGROINDO         Indonesia      6
17         FELCRA PROCESSING & ENGINEERING SDN BHD          Malaysia      6
18                             TH INDO PLANTATIONS         Indonesia      6
19                            NEW BRITAIN PALM OIL  Papua New Guinea      5
20                          UNITED PLANTATIONS BHD          Malaysia      5
21           UNIVANICH PALM OIL PUBLIC COMPANY LTD          Thailand      5
22                          DHARMA SATYA NUSANTARA         Indonesia      5
23         SINAR MAS AGRO RESOURCES AND TECHNOLOGY         Indonesia      4
24                                TAPIAN NADENGGAN         Indonesia      4

In [5]:
# Colgate Mill owners in Indonesia (Parent Companies)
colgate_mill_owners = colgate_mill_owners[colgate_mill_owners["Country"] == "Indonesia"].reset_index()
colgate_mill_owners.drop(columns = "index", inplace = True)

In [6]:
# Total Colgate Mill Owners in Indonesia
t_colgate_owners = colgate_mill_owners["count"].sum()
print(f"Total Colgate Mill Owners in Indonesia: {t_colgate_owners}")

Total Colgate Mill Owners in Indonesia: 1010

In [7]:
colgate_mill.head(25)

,UML ID,years,Group Name,Parent Company,Mill Name,RSPO Status,RSPO Type,Date RSPO Certification Status,Latitude,Longitude,...,treeloss_ha_2021,treeloss_km_2022,treeloss_ha_2022,sum_of_treeloss_km,treeloss_sum_proportion_of_forest,remaining_forest_km,remaining_proportion_of_forest,Current Deforestation Score,Past Deforestation Score,Future Risk Score
0,PO1000000019,"2021,2020,2019,2018,2017",KULIM (MALAYSIA) BERHAD,EPA MANAGEMENT SDN BHD,SEDENAK,RSPO Certified,"RSPO Certified, MB",3/31/23,1.73,103.54,...,321.48,1.63,162.72,94.74,0.74,32.73,0.26,3,4,3
1,PO1000000020,2018,NBPOL,NEW BRITAIN PALM OIL,MOSA,RSPO Certified,"RSPO Certified, IP",3/31/23,-5.62,150.24,...,820.62,7.76,775.80,119.11,0.07,1666.81,0.93,2,1,3
2,PO1000000021,"2018,2017,2020,2021,2019",ROYAL GOLDEN EAGLE,INTI INDOSAWIT SUBUR,BUATAN I,RSPO Certified,"RSPO Certified, MB",3/31/23,0.43,101.82,...,112.95,1.00,99.72,51.22,0.64,29.00,0.36,3,4,3
3,PO1000000052,"2021,2019,2018,2020",IOI CORPORATION,PAMOL ESTATES (SABAH) SDN BHD,PAMOL SABAH,RSPO Certified,"RSPO Certified, IP",3/31/23,6.00,117.40,...,265.32,4.37,436.59,238.78,0.77,69.49,0.23,3,4,2
4,PO1000000054,"2021,2019,2017,2018",MUSIM MAS,MUSIM MAS HOLDINGS PTE LTD,BATANG KULIM,RSPO Certified,"RSPO Certified, IP",3/31/23,0.08,102.03,...,511.47,9.88,987.75,226.85,0.84,42.36,0.16,4,5,3
5,PO1000000058,"2017,2018,2020,2019,2021",CARGILL,HINDOLI,SUNGAI LILIN,RSPO Certified,"RSPO Certified, IP",3/31/23,-2.61,104.13,...,161.01,2.63,263.07,49.68,0.72,19.19,0.28,4,4,3
6,PO1000000063,"2019,2020,2018,2017",SIME DARBY,SIME DARBY PLANTATION BHD,BINUANG (SOU 28),RSPO Certified,"RSPO Certified, IP",3/31/23,4.70,118.06,...,261.54,2.49,248.85,103.19,0.49,108.35,0.51,3,3,3
7,PO1000000064,"2018,2017,2019,2020",SIME DARBY,SIME DARBY PLANTATION BHD,MEROTAI (SOU 30),RSPO Certified,"RSPO Certified, MB",3/31/23,4.37,117.83,...,1237.95,12.48,1248.03,144.00,0.30,334.64,0.70,4,2,4
8,PO1000000065,"2020,2018,2019",SIME DARBY,SIME DARBY PLANTATION BHD,SANDAKAN BAY (SOU 26),RSPO Certified,"RSPO Certified, MB",3/31/23,5.64,118.17,...,931.23,7.61,760.68,137.38,0.43,180.24,0.57,4,3,4
9,PO1000000066,"2019,2017,2018",WILMAR GROUP,SABAHMAS PLANTATION SDN BHD,SABAHMAS,RSPO Certified,"RSPO Certified, MB",3/31/23,5.18,118.41,...,953.46,2.10,210.33,89.29,1.00,0.00,0.00,5,5,3
10,PO1000000091,"2017,2018,2020,2021,2019",WILMAR GROUP,SAREMAS SDN BHD,SAREMAS 1,RSPO Certified,"RSPO Certified, MB",3/31/23,3.52,113.74,...,44.10,0.69,68.76,117.32,1.00,0.38,0.00,2,5,1
11,PO1000000092,2019,MUSIM MAS,AGRO WIRATAMA,AGROWIRATAMA,RSPO Certified,"RSPO Certified, IP",3/31/23,0.20,99.63,...,1883.88,7.98,798.03,231.50,0.77,70.72,0.23,5,4,3
12,PO1000000093,"2019,2021,2017,2018,2020",WILMAR GROUP,SAREMAS SDN BHD,SAREMAS 2,RSPO Certified,"RSPO Certified, IP",3/31/23,3.45,113.77,...,1879.11,6.09,609.21,142.53,0.89,17.04,0.11,5,5,4
13,PO1000000094,"2021,2020,2019,2018,2017",IOI CORPORATION,IOI CORPORATION BHD,GOMALI,RSPO Certified,"RSPO Certified, IP",3/31/23,2.61,102.68,...,304.47,3.75,374.76,138.82,0.91,12.92,0.09,3,5,2
14,PO1000000095,"2018,2017,2021,2020,2019",SIPEF,EASTERN SUMATERA INDONESIA,BUKIT MARADJA,RSPO Certified,"RSPO Certified, IP",3/31/23,3.01,99.24,...,76.95,0.99,98.55,29.64,0.83,6.23,0.17,4,5,3
15,PO1000000097,"2019,2018,2020,2021",SIME DARBY,SIME DARBY PLANTATION BHD,EAST (SOU 8),RSPO Certified,"RSPO Certified, IP",3/31/23,2.88,101.44,...,232.29,1.11,111.24,39.13,0.53,35.34,0.47,3,3,3
16,PO1000000098,"2020,2021,2019,2018",SIME DARBY,SIME DARBY PLANTATION BHD,TANAH MERAH (SOU 14),RSPO Certified,"RSPO Certified, IP",3/31/23,2.66,101.79,...,293.13,3.12,312.48,94.51,0.88,13.30,0.12,4,5,3
17,PO1000000099,"2017,2018,2020,2021,2019",SIPEF,TOLAN TIGA INDONESIA,PERLABIAN,RSPO Certified,"RSPO Certified, IP",3/31/23,2.06,100.08,...,103.50,3.04,303.75,72.95,0.65,38.60,0.35,3,4,3
18,PO1000000103,"2019,2017,2018,2020,2021",SIME DARBY,SIME DARBY PLANTATION BHD,WEST (SOU 9),RSPO Certified,"RSPO Certified, IP",3/31/23,2.90,101.36,...,352.98,3.05,304.74,91.24,0.46,105.26,0.54,3,3,3
19,PO1000000104,"2020,2021,2019,2018,2017",SIME DARBY,SIME DARBY PLANTATION BHD,SUNGAI DINGIN (SOU 1),RSPO Certified,"RSPO Certified, MB",3/31/23,5.39,100.71,...,541.89,5.81,580.86,103.95,0.30,243.83,0.70,3,2,3
20,PO1000000106,2019,MUSIM MAS,SUKAJADI SAWIT MEKAR,SUKAJADI SAWIT MEKAR 1,RSPO Certified,"RSPO Certified, IP",3/31/23,-2.38,112.54,...,171.81,1.83,182.61,160.69,1.00,0.38,0.00,3,5,1
21,PO1000000107,"2019,2020,2021,2017,2018",SIME DARBY,SIME INDO AGRO,BUKIT AJONG,RSPO Certified,"RSPO Certified, MB",3/31/23,0.27,110.48,...,2362.68,9.24,923.85,294.65,0.70,129.06,0.30,5,4,3
22,PO1000000109,"2017,2018,2019,2020,2021",IOI CORPORATION,IOI CORPORATION BHD,PAMOL KLUANG,RSPO Certified,"RSPO Certified, IP",3/31/23,2.11,103.39,...,424.89,1.79,179.01,117.25,0.81,27.48,0.19,3,5,3
23,PO1000000110,"2020,2018,2017,2021,2019",IOI CORPORATION,IOI CORPORATION BHD,SAKILAN,RSPO Certified,"RSPO Certified, IP",3/31/23,5.84,117.84,...,181.89,2.13,213.48,48.16,0.55,39.20,0.45,3,3,3
24,PO1000000118,"2019,2021,2020,2017,2018",IOI CORPORATION,IOI CORPORATION BHD,BATURONG,RSPO Certified,"RSPO Certified, IP",3/31/23,4.76,118.09,...,121.68,3.89,389.25,63.29,0.98,1.36,0.02,5,5,3

In [8]:
colgate_mill_cols = colgate_mill.columns
colgate_mill_cols

Index(['UML ID', 'years', 'Group Name', 'Parent Company', 'Mill Name',
       'RSPO Status', 'RSPO Type', 'Date RSPO Certification Status',
       'Latitude', 'Longitude', 'GPS coordinates', 'ISO', 'Country',
       'Province', 'District', 'Confidence level', 'Alternative name',
       'km_forest_area_00', 'ha_forest_area_00', 'km_area', 'km_0', 'ha_0',
       'treeloss_km_2001', 'treeloss_ha_2001', 'treeloss_km_2002',
       'treeloss_ha_2002', 'treeloss_km_2003', 'treeloss_ha_2003',
       'treeloss_km_2004', 'treeloss_ha_2004', 'treeloss_km_2005',
       'treeloss_ha_2005', 'treeloss_km_2006', 'treeloss_ha_2006',
       'treeloss_km_2007', 'treeloss_ha_2007', 'treeloss_km_2008',
       'treeloss_ha_2008', 'treeloss_km_2009', 'treeloss_ha_2009',
       'treeloss_km_2010', 'treeloss_ha_2010', 'treeloss_km_2011',
       'treeloss_ha_2011', 'treeloss_km_2012', 'treeloss_ha_2012',
       'treeloss_km_2013', 'treeloss_ha_2013', 'treeloss_km_2014',
       'treeloss_ha_2014', 'treeloss_km_2015', 'treeloss_ha_2015',
       'treeloss_km_2016', 'treeloss_ha_2016', 'treeloss_km_2017',
       'treeloss_ha_2017', 'treeloss_km_2018', 'treeloss_ha_2018',
       'treeloss_km_2019', 'treeloss_ha_2019', 'treeloss_km_2020',
       'treeloss_ha_2020', 'treeloss_km_2021', 'treeloss_ha_2021',
       'treeloss_km_2022', 'treeloss_ha_2022', 'sum_of_treeloss_km',
       'treeloss_sum_proportion_of_forest', 'remaining_forest_km',
       'remaining_proportion_of_forest', 'Current Deforestation Score',
       'Past Deforestation Score', 'Future Risk Score'],
      dtype='object')

In [9]:
# Clean the dataframes and only save the rows with Sumatra provinces
def prepare_df(df):

  """
  Create a dataframe with only information of Sumatra, Indonesia
  """

  # Save data from Sumatra in specific (cut the rest of the columns and rows)
  df = df[df["Province"].isin(provinces)]

  # Save the columns we consider important
  df = df.loc[:, "UML ID":"sum_of_treeloss_km"].reset_index()
  df.drop(columns = df.loc[:, "Confidence level" : "treeloss_ha_2022"], inplace = True)

  # Sort data by province and parent company columns
  df_prov = df.loc[:, ["Province", "Parent Company", "RSPO Status", "sum_of_treeloss_km"]].sort_values(by = ["Province", "Parent Company"])

  return df_prov

In [10]:
# Save data from Sumatra in specific (cut the rest of the columns and rows)
colgate_pmill = prepare_df(colgate_mill)
colgate_pmill

,Province,Parent Company,RSPO Status,sum_of_treeloss_km
391,Aceh,ANUGRAH FAJAR REZEKI,Not RSPO Certified,85.64
218,Aceh,BANGUN SEMPURNA LESTARI,Not RSPO Certified,397.91
234,Aceh,BEURATA SUBUR PERSADA,Not RSPO Certified,278.23
393,Aceh,BLANG KETUMBA,Not RSPO Certified,494.62
392,Aceh,BOSWA MEGALOPOLIS,Not RSPO Certified,527.55
...,...,...,...,...
68,Sumatera Utara,UMBUL MAS WISESA,RSPO Certified,197.00
257,Sumatera Utara,UNITED KINGDOM INDONESIA PLANTATION,Not RSPO Certified,26.22
481,Sumatera Utara,VAREM SAWIT CEMERLANG,Not RSPO Certified,92.82
453,Sumatera Utara,VICTORINDO ALAM LESTARI,Not RSPO Certified,321.54
553,Sumatera Utara,YAPUTRA ALFA PALMINDO,Not RSPO Certified,14.09

In [11]:
colgate_pmill["Parent Company"].nunique()

523

In [12]:
# Count the amount of mills the company has in each Sumatra province
def mill_quantity(company_list):

  """
  This function takes the list of all the company dataframes and calculates the amount
  of mills they posses in each region and the amount of tree loss they've caused.

  Returns a dataframe with the information calculated.
  """

  # Create dataframe
  company_df = pd.DataFrame()

  # Iterate through the company dataframes and provinces
  for company in company_list:
    for p in provinces:

      # Temporary df with information of a specific province
      temp = company[company["Province"] == p]
      print(temp)

In [20]:
# Create dataframe
company_dict = {}
company_df = pd.DataFrame()

company_df["Company"] = companies
companies
# for p in provinces:
#     # Temporary df with information of a specific province
#     temp = company[company["Province"] == p]
#     mill_column = p + "_mill_count"
#     tree_loss_column = p + "_tree_loss_km"
#     company_df.at[company, mill_column] = temp["Parent Company"].nunique()
#     company_df.at[company, tree_loss_column] = temp["sum_of_treeloss_km"].sum()

[            UML ID                     years               Group Name  \
 0     PO1000000019  2021,2020,2019,2018,2017  KULIM (MALAYSIA) BERHAD
 1     PO1000000020                      2018                    NBPOL
 2     PO1000000021  2018,2017,2020,2021,2019       ROYAL GOLDEN EAGLE
 3     PO1000000052       2021,2019,2018,2020          IOI CORPORATION
 4     PO1000000054       2021,2019,2017,2018                MUSIM MAS
 ...            ...                       ...                      ...
 1679  PO1000012845                      2021                  UNKNOWN
 1680  PO1000012846                      2021                  UNKNOWN
 1681  PO1000012848            2021,2019,2020                  UNKNOWN
 1682  PO1000012851                      2021                  UNKNOWN
 1683  PO1000012852                      2021                  UNKNOWN

                      Parent Company                  Mill Name  \
 0            EPA MANAGEMENT SDN BHD                    SEDENAK
 1              NEW BRITAIN PALM OIL                       MOSA
 2              INTI INDOSAWIT SUBUR                   BUATAN I
 3     PAMOL ESTATES (SABAH) SDN BHD                PAMOL SABAH
 4        MUSIM MAS HOLDINGS PTE LTD               BATANG KULIM
 ...                             ...                        ...
 1679        SANLING SAWIT SEJATERA     SANLING SAWIT SEJATERA
 1680          PT CITRA AGRO KENCANA    CITRA AGRO KENCANA MILL
 1681                     ARSI GROUP     ARSI GRIYA PLANTATIONS
 1682            BUKIT JEJER SUKSES         BUKIT JEJER SUKSES
 1683      YUNI BERSAUDARA SEJAHTERA  YUNI BERSAUDARA SEJAHTERA

              RSPO Status           RSPO Type Date RSPO Certification Status  \
 0         RSPO Certified  RSPO Certified, MB                        3/31/23
 1         RSPO Certified  RSPO Certified, IP                        3/31/23
 2         RSPO Certified  RSPO Certified, MB                        3/31/23
 3         RSPO Certified  RSPO Certified, IP                        3/31/23
 4         RSPO Certified  RSPO Certified, IP                        3/31/23
 ...                  ...                 ...                            ...
 1679  Not RSPO Certified                 NaN                        3/31/23
 1680  Not RSPO Certified                 NaN                        3/31/23
 1681  Not RSPO Certified                 NaN                        3/31/23
 1682  Not RSPO Certified                 NaN                        3/31/23
 1683  Not RSPO Certified                 NaN                        3/31/23

       Latitude  Longitude  ... treeloss_ha_2021 treeloss_km_2022  \
 0         1.73     103.54  ...           321.48             1.63
 1        -5.62     150.24  ...           820.62             7.76
 2         0.43     101.82  ...           112.95             1.00
 3         6.00     117.40  ...           265.32             4.37
 4         0.08     102.03  ...           511.47             9.88
 ...        ...        ...  ...              ...              ...
 1679     -0.38     102.16  ...           104.67             0.75
 1680     -0.47     115.59  ...          3045.69            23.53
 1681     -2.86     104.94  ...            97.83             0.38
 1682     -2.29     121.79  ...           659.52            11.66
 1683     -0.03     101.19  ...          3695.49            40.01

      treeloss_ha_2022 sum_of_treeloss_km treeloss_sum_proportion_of_forest  \
 0              162.72              94.74                              0.74
 1              775.80             119.11                              0.07
 2               99.72              51.22                              0.64
 3              436.59             238.78                              0.77
 4              987.75             226.85                              0.84
 ...               ...                ...                               ...
 1679            74.52              45.40                              0.63
 1680          2353.32            1199.13                              0.29
 1681            37.62              45.72                              0.88
 1682          1166.04             251.21                              0.15
 1683          4000.59             667.27                              0.27

      remaining_forest_km remaining_proportion_of_forest  \
 0                  32.73                           0.26
 1                1666.81                           0.93
 2                  29.00                           0.36
 3                  69.49                           0.23
 4                  42.36                           0.16
 ...                  ...                            ...
 1679               26.20                           0.37
 1680             2976.48                           0.71
 1681                6.05                           0.12
 1682             1406.25                           0.85
 1683             1782.05                           0.73

       Current Deforestation Score  Past Deforestation Score  Future Risk Score
 0                               3                         4                  3
 1                               2                         1                  3
 2                               3                         4                  3
 3                               3                         4                  2
 4                               4                         5                  3
 ...                           ...                       ...                ...
 1679                            3                         3                  3
 1680                            2                         2                  3
 1681                            3                         5                  2
 1682                            2                         1                  3
 1683                            3                         2                  3

 [1684 rows x 73 columns],
            UML ID                years               Group Name  \
 0    PO1000000017            2019,2021                AGROPALMA
 1    PO1000000019            2019,2020  KULIM (MALAYSIA) BERHAD
 2    PO1000000020  2020,2021,2018,2019                    NBPOL
 3    PO1000000052            2020,2021          IOI CORPORATION
 4    PO1000000053  2021,2018,2019,2020                    SIPEF
 ..            ...                  ...                      ...
 764  PO1000011306                 2021      DHARMA AGUNG WIJAYA
 765  PO1000011478                 2021                  UNKNOWN
 766  PO1000011552                 2021                  UNKNOWN
 767  PO1000011553                 2021                  UNKNOWN
 768  PO1000011916                 2020                  UNKNOWN

                          Parent Company                   Mill Name  \
 0                             AGROPALMA                         CPA
 1                EPA MANAGEMENT SDN BHD                     SEDENAK
 2                  NEW BRITAIN PALM OIL                        MOSA
 3         PAMOL ESTATES (SABAH) SDN BHD                 PAMOL SABAH
 4                    HARGY OIL PALM LTD                  HARGY MILL
 ..                                  ...                         ...
 764          PT HANUSENTRA AGRO LESTARI  PT HANUSENTRA AGRO LESTARI
 765                      SINDORA SERAYA              SINDORA SERAYA
 766              PARENTNAME IS MILLNAME  LANGKAT MAKMUR JAYA SAWITA
 767  DUPONT & LEOSK ENTERPRISES SDN BHD          GASING SAWIT ABADI
 768                NEW BRITAIN PALM OIL                    NARANGIT

             RSPO Status           RSPO Type Date RSPO Certification Status  \
 0    Not RSPO Certified                 NaN                        3/31/23
 1        RSPO Certified  RSPO Certified, MB                        3/31/23
 2        RSPO Certified  RSPO Certified, IP                        3/31/23
 3        RSPO Certified  RSPO Certified, IP                        3/31/23
 4        RSPO Certified  RSPO Certified, IP                        3/31/23
 ..                  ...                 ...                            ...
 764  Not RSPO Certified                 NaN                        3/31/23
 765  Not RSPO Certified                 NaN                        3/31/23
 766  Not RSPO Certified                 NaN                        3/31/23
 767  Not RSPO Certified                 NaN                        3/31/23
 768  Not RSPO Certified                 NaN                        3/31/23

      Latitude  Longitude  ... treeloss_ha_2021 treeloss_km_2022  \
 0       -2.25     -48.59  ...           214.92             2.11
 1        1.73     103.54  ...           321.48             1.63
 2       -5.62     150.24  ...           820.62             7.76
 3        6.00     117.40  ...           265.32             4.37
 4       -5.31     151.01  ...           640.08            14.17
 ..        ...        ...  ...              ...              ...
 764      1.18     117.90  ...            30.69             0.41
 765      1.89     100.95  ...          2146.86            26.45
 766      3.88      98.34  ...           212.76             1.90
 767     -2.56     104.77  ...          1274.85             6.16
 768     -4.36     151.95  ...          7207.11           314.43

     treeloss_ha_2022 sum_of_treeloss_km treeloss_sum_proportion_of_forest  \
 0             210.60             104.56                              0.27
 1             162.72              94.74                              0.74
 2             775.80             119.11                              0.07
 3             436.59             238.78                              0.77
 4            1416.78             100.81                              0.09
 ..               ...                ...                               ...
 764            41.22             221.14                              0.62
 765          2645.19             663.81                              0.46
 766           190.26              31.70                              0.49
 767           616.14             326.44                              0.65
 768         31443.39            1044.47                              0.22

     remaining_forest_km remaining_proportion_of_forest  \
 0                284.88                           0.73
 1                 32.73                           0.26
 2               1666.81                           0.93
 3                 69.49                           0.23
 4               1040.02                           0.91
 ..                  ...                            ...
 764              133.70                           0.38
 765              785.63                           0.54
 766               33.48                           0.51
 767              173.38                           0.35
 768             3664.61                           0.78

      Current Deforestation Score  Past Deforestation Score  Future Risk Score
 0                              2                         2                  3
 1                              3                         4                  3
 2                              2                         1                  3
 3                              3                         4                  2
 4                              3                         1                  3
 ..                           ...                       ...                ...
 764                            1                         3                  2
 765                            3                         3                  3
 766                            4                         3                  4
 767                            3                         4                  3
 768                            5                         1                  5

 [769 rows x 73 columns],
             UML ID                     years               Group Name  \
 0     PO1000000019  2020,2021,2019,2017,2018  KULIM (MALAYSIA) BERHAD
 1     PO1000000020            2018,2020,2019                    NBPOL
 2     PO1000000021  2020,2018,2017,2021,2019       ROYAL GOLDEN EAGLE
 3     PO1000000052  2019,2020,2021,2018,2017          IOI CORPORATION
 4     PO1000000053            2018,2020,2019                    SIPEF
 ...            ...                       ...                      ...
 1663  PO1000012844                      2020                  UNKNOWN
 1664  PO1000012845                      2020                  UNKNOWN
 1665  PO1000012846                 2020,2021                  UNKNOWN
 1666  PO1000012848                 2019,2020                  UNKNOWN
 1667  PO1000012852                      2020                  UNKNOWN

                      Parent Company                  Mill Name  \
 0            EPA MANAGEMENT SDN BHD                    SEDENAK
 1              NEW BRITAIN PALM OIL                       MOSA
 2              INTI INDOSAWIT SUBUR                   BUATAN I
 3     PAMOL ESTATES (SABAH) SDN BHD                PAMOL SABAH
 4                HARGY OIL PALM LTD                 HARGY MILL
 ...                             ...                        ...
 1663               SAWIT INTI RAYA            SAWIT INTI RAYA
 1664        SANLING SAWIT SEJATERA     SANLING SAWIT SEJATERA
 1665          PT CITRA AGRO KENCANA    CITRA AGRO KENCANA MILL
 1666                     ARSI GROUP     ARSI GRIYA PLANTATIONS
 1667      YUNI BERSAUDARA SEJAHTERA  YUNI BERSAUDARA SEJAHTERA

              RSPO Status           RSPO Type Date RSPO Certification Status  \
 0         RSPO Certified  RSPO Certified, MB                        3/31/23
 1         RSPO Certified  RSPO Certified, IP                        3/31/23
 2         RSPO Certified  RSPO Certified, MB                        3/31/23
 3         RSPO Certified  RSPO Certified, IP                        3/31/23
 4         RSPO Certified  RSPO Certified, IP                        3/31/23
 ...                  ...                 ...                            ...
 1663  Not RSPO Certified                 NaN                        3/31/23
 1664  Not RSPO Certified                 NaN                        3/31/23
 1665  Not RSPO Certified                 NaN                        3/31/23
 1666  Not RSPO Certified                 NaN                        3/31/23
 1667  Not RSPO Certified                 NaN                        3/31/23

       Latitude  Longitude  ... treeloss_ha_2021 treeloss_km_2022  \
 0         1.73     103.54  ...           321.48             1.63
 1        -5.62     150.24  ...           820.62             7.76
 2         0.43     101.82  ...           112.95             1.00
 3         6.00     117.40  ...           265.32             4.37
 4        -5.31     151.01  ...           640.08            14.17
 ...        ...        ...  ...              ...              ...
 1663     -0.46     102.17  ...          1096.29             7.82
 1664     -0.38     102.16  ...           104.67             0.75
 1665     -0.47     115.59  ...          3045.69            23.53
 1666     -2.86     104.94  ...            97.83             0.38
 1667     -0.03     101.19  ...          3695.49            40.01

      treeloss_ha_2022 sum_of_treeloss_km treeloss_sum_proportion_of_forest  \
 0              162.72              94.74                              0.74
 1              775.80             119.11                              0.07
 2               99.72              51.22                              0.64
 3              436.59             238.78                              0.77
 4             1416.78             100.81                              0.09
 ...               ...                ...                               ...
 1663           782.28             232.76                              0.71
 1664            74.52              45.40                              0.63
 1665          2353.32            1199.13                              0.29
 1666            37.62              45.72                              0.88
 1667          4000.59             667.27                              0.27

      remaining_forest_km remaining_proportion_of_forest  \
 0                  32.73                           0.26
 1                1666.81                           0.93
 2                  29.00                           0.36
 3                  69.49                           0.23
 4                1040.02                           0.91
 ...                  ...                            ...
 1663               96.42                           0.29
 1664               26.20                           0.37
 1665             2976.48                           0.71
 1666                6.05                           0.12
 1667             1782.05                           0.73

       Current Deforestation Score  Past Deforestation Score  Future Risk Score
 0                               3                         4                  3
 1                               2                         1                  3
 2                               3                         4                  3
 3                               3                         4                  2
 4                               3                         1                  3
 ...                           ...                       ...                ...
 1663                            4                         4                  3
 1664                            3                         3                  3
 1665                            2                         2                  3
 1666                            3                         5                  2
 1667                            3                         2                  3

 [1668 rows x 73 columns],
             UML ID                years               Group Name  \
 0     PO1000000019  2019,2021,2018,2017  KULIM (MALAYSIA) BERHAD
 1     PO1000000020                 2017                    NBPOL
 2     PO1000000021            2017,2018       ROYAL GOLDEN EAGLE
 3     PO1000000052  2019,2021,2018,2017          IOI CORPORATION
 4     PO1000000053                 2017                    SIPEF
 ...            ...                  ...                      ...
 1393  PO1000011917                 2021                  UNKNOWN
 1394  PO1000011992                 2021                  UNKNOWN
 1395  PO1000012424                 2021                  UNKNOWN
 1396  PO1000012622                 2021                  UNKNOWN
 1397  PO1000012852                 2021                  UNKNOWN

                      Parent Company                           Mill Name  \
 0            EPA MANAGEMENT SDN BHD                             SEDENAK
 1              NEW BRITAIN PALM OIL                                MOSA
 2              INTI INDOSAWIT SUBUR                            BUATAN I
 3     PAMOL ESTATES (SABAH) SDN BHD                         PAMOL SABAH
 4                HARGY OIL PALM LTD                          HARGY MILL
 ...                             ...                                 ...
 1393      HAP SENG CONSOLIDATED BHD                 MITRA KARYA SENTOSA
 1394          SELARAS MITRA SARIMBA                          GIRI PURNO
 1395           WIJAYA BOMEO TIGANNA  WIJAYA BORNEO TIGANNA BATANG KULUR
 1396                  PALMARIS RAYA                       PALMARIS RAYA
 1397      YUNI BERSAUDARA SEJAHTERA           YUNI BERSAUDARA SEJAHTERA

              RSPO Status           RSPO Type Date RSPO Certification Status  \
 0         RSPO Certified  RSPO Certified, MB                        3/31/23
 1         RSPO Certified  RSPO Certified, IP                        3/31/23
 2         RSPO Certified  RSPO Certified, MB                        3/31/23
 3         RSPO Certified  RSPO Certified, IP                        3/31/23
 4         RSPO Certified  RSPO Certified, IP                        3/31/23
 ...                  ...                 ...                            ...

In [13]:
# Calculate total colgate mills per province
colgate_mill_count = {}

for p in provinces:
  data = {"Mill Count": 0, "Treeloss km": 0}
  temp = colgate_pmill[colgate_pmill["Province"] == p]
  data["Mill Count"] = temp["Parent Company"].nunique()
  data["Treeloss km"] = temp["sum_of_treeloss_km"].sum()
  colgate_mill_count[p] = data

colgate_mill_count

{'Aceh': {'Mill Count': 34, 'Treeloss km': np.float64(5990.11)},
 'Riau': {'Mill Count': 177, 'Treeloss km': np.float64(44379.99)},
 'Bengkulu': {'Mill Count': 25, 'Treeloss km': np.float64(4378.83)},
 'Sumatera Selatan': {'Mill Count': 61, 'Treeloss km': np.float64(26717.66)},
 'Sumatera Barat': {'Mill Count': 30, 'Treeloss km': np.float64(5905.2)},
 'Sumatera Utara': {'Mill Count': 134,
  'Treeloss km': np.float64(16137.759999999998)},
 'Jambi': {'Mill Count': 64, 'Treeloss km': np.float64(18600.66)},
 'Lampung': {'Mill Count': 14, 'Treeloss km': np.float64(3641.4100000000003)}}